import test from 'node:test';
import assert from 'node:assert/strict';
import { analyze, compare, plan, validDate, addDays, validateBackup } from '../src/engine.js';
const base='2026-09-06';
const task=(id,due,minutes,extra={})=>({id,title:id,source:'물리 보고서',sourceDate:base,fields:{...analyze('물리 보고서',base).fields,due},minutes,priority:2,done:false,history:[],...extra});
test('tomorrow uses notice date, not current clock',()=>assert.equal(analyze('내일 물리 보고서 2쪽',base).fields.due,'2026-09-07'));
test('day after tomorrow crosses year',()=>assert.equal(analyze('모레 제출','2026-12-31').fields.due,'2027-01-02'));
test('next Tuesday uses Monday-based week on Sunday',()=>assert.equal(analyze('다음 주 화요일 제출',base).fields.due,'2026-09-08'));
test('this Tuesday can be in the past and is not silently rolled forward',()=>assert.equal(analyze('이번 주 화요일 제출',base).fields.due,'2026-09-01'));
test('bare weekday resolves nearest current/future date',()=>assert.equal(analyze('목요일 물리 수행',base).fields.due,'2026-09-10'));
test('a vague week does not invent a date',()=>assert.equal(analyze('다음 주 물리 수행',base).fields.due,null));
test('ISO date is not double parsed',()=>assert.equal(analyze('2026-09-10 제출',base).fields.due,'2026-09-10'));
test('Korean explicit date',()=>assert.equal(analyze('2026년 9월 10일 제출',base).fields.due,'2026-09-10'));
test('month day uses stated reference year',()=>assert.equal(analyze('9월 10일 제출',base).fields.due,'2026-09-10'));
test('two date candidates require confirmation',()=>{const a=analyze('9/10에서 9/8로 변경',base);assert.equal(a.fields.due,null);assert.ok(a.issues.some(s=>s.includes('여러 개')));});
test('nonexistent date rejected',()=>{const a=analyze('2026-02-30 제출',base);assert.equal(a.fields.due,null);assert.ok(a.issues.length);});
test('valid leap day and invalid reference date',()=>{assert.ok(validDate('2028-02-29'));assert.equal(validDate('2026-02-29'),false);assert.throws(()=>analyze('내일 제출','2026-13-01'));});
test('AM midnight and PM time',()=>{assert.equal(analyze('오후 5시 제출',base).fields.time,'17:00');assert.equal(analyze('오전 12시 제출',base).fields.time,'00:00');});
test('invalid times remain unknown',()=>assert.equal(analyze('29시 70분 제출',base).fields.time,null));
test('semantic quantity, subject, labeled place and materials',()=>{const a=analyze('물리 보고서 4쪽\n장소: 물리실\n준비물: 자, 연필',base);assert.equal(a.fields.subject,'물리');assert.equal(a.fields.amount,'4쪽');assert.equal(a.fields.materials,'자, 연필');assert.equal(a.fields.place,'물리실');});
test('conflicting labeled values are not chosen arbitrarily',()=>{const a=analyze('장소: 201호\n장소: 301호',base);assert.equal(a.fields.place,null);assert.ok(a.issues.some(x=>x.includes('장소 후보')));});
test('cancel expression is a warning not auto deletion',()=>assert.ok(analyze('물리 수행 취소 여부 추후 안내',base).issues.some(x=>x.includes('취소'))));
test('missing items generate questions',()=>assert.ok(analyze('물리 수행',base).questions.length>=4));
test('identical notice has no changes',()=>assert.deepEqual(compare(analyze('물리 9/10 PDF 2쪽',base),analyze('물리 9/10 PDF 2쪽',base)),[]));
test('removed mention requires confirmation rather than cancellation',()=>{const d=compare(analyze('물리 9/10 PDF 2쪽',base),analyze('물리 9/10',base));assert.equal(d.find(x=>x.key==='format').kind,'확인 필요');});
test('changes retain old and new evidence',()=>{const d=compare(analyze('9/10 물리 보고서 2쪽',base),analyze('9/8 물리 보고서 4쪽',base));assert.equal(d.find(x=>x.key==='due').after,'2026-09-08');assert.equal(d.find(x=>x.key==='amount').oldEvidence,'2쪽');});
test('capacity never exceeded and work conserved including overflow',()=>{const tasks=[task('a','2026-09-08',240),task('b','2026-09-08',120),task('c','2026-09-07',90)];const p=plan(tasks,90,base);assert.equal(p.totalShortage,180);assert.ok(p.days.every(d=>d.used<=90));assert.equal(p.days.reduce((n,d)=>n+d.used,0)+p.totalShortage,450);});
test('reverse planning places a small task near its deadline',()=>{const p=plan([task('a','2026-09-08',60)],90,base);assert.equal(p.days[2].used,60);assert.equal(p.days[0].used,0);});
test('earlier deadline reserves capacity before later deadlines',()=>{const p=plan([task('later','2026-09-07',180),task('early',base,90)],90,base);assert.equal(p.days[0].items[0].id,'early');assert.equal(p.totalShortage,90);});
test('done and unknown deadline tasks not scheduled',()=>{const p=plan([task('a',base,90,{done:true}),task('b',null,100)],90,base);assert.equal(p.days[0].used,0);assert.deepEqual(p.missing,['b']);});
test('past deadline becomes explicit overflow',()=>assert.equal(plan([task('late','2026-09-01',60)],90,base).overflow[0].reason,'마감 지남'));
test('distant tasks stay outside the 14-day window',()=>{const p=plan([task('future','2027-01-01',1000)],90,base);assert.equal(p.totalShortage,0);assert.equal(p.days.reduce((n,d)=>n+d.used,0),0);});
test('priority resolves equal deadlines',()=>{const p=plan([task('low',base,90,{priority:1}),task('high',base,90,{priority:3})],90,base);assert.equal(p.days[0].items[0].id,'high');});
test('backup validation rejects malformed fields and duplicate ids',()=>{const good={version:1,capacity:90,tasks:[task('a',base,60)]};assert.ok(validateBackup(good));assert.equal(validateBackup({...good,tasks:[...good.tasks,...good.tasks]}),false);assert.equal(validateBackup({...good,capacity:-5}),false);assert.equal(validateBackup({...good,tasks:[{...good.tasks[0],fields:{}}]}),false);});
test('date increments survive month boundary',()=>assert.equal(addDays('2026-09-30',1),'2026-10-01'));
