import webpush from 'web-push';
import {autoGroupScopes,canAccessRoom} from './auto-groups.js';
export const pushEnabled=()=>!!process.env.VAPID_PUBLIC_KEY&&!!process.env.VAPID_PRIVATE_KEY;
export function validSubscription(s){try{const u=new URL(s.endpoint);return s.endpoint.length<2000&&u.protocol==='https:'&&!u.username&&!u.password&&!u.hash&&(!u.port||u.port==='443')&&(u.hostname==='fcm.googleapis.com'||u.hostname.endsWith('.push.services.mozilla.com')||u.hostname==='web.push.apple.com'||u.hostname.endsWith('.notify.windows.com'))&&/^[\w-]{80,100}$/.test(s.keys?.p256dh)&&/^[\w-]{20,30}$/.test(s.keys?.auth);}catch{return false;}}
export async function notifyPeers(sql,sender,room=null,classId=null){
 if(!pushEnabled())return;
 const [senderMember]=room?.auto_key?await sql`SELECT c.school,c.grade,c.class_name FROM public.campus_members m JOIN public.campus_classes c ON c.id=m.class_id WHERE m.user_id=${sender}`:[];
 const peers=await sql`SELECT d.endpoint,d.subscription,d.user_id,p.school,p.grade,p.class_name,p.discoverable,c.school AS verified_school,c.grade AS verified_grade,c.class_name AS verified_class,m.class_id FROM public.campus_push d JOIN public.campus_people p ON p.user_id=d.user_id JOIN public.campus_members m ON m.user_id=p.user_id JOIN public.campus_classes c ON c.id=m.class_id WHERE d.user_id<>${sender} AND ((${classId!==null} AND m.class_id=${classId}::uuid) OR (${!classId&&!room?.auto_key} AND d.user_id=ANY(${room?.members||[]}::text[])) OR (${!!room?.auto_key} AND c.school=${senderMember?.school||''} AND (${room?.auto_kind==='school'} OR (c.grade=${senderMember?.grade||''} AND c.class_name=${senderMember?.class_name||''})))) AND p.discoverable=true AND NOT EXISTS(SELECT 1 FROM public.campus_accounts a WHERE a.user_id=d.user_id AND a.suspended=true) AND NOT EXISTS(SELECT 1 FROM public.campus_blocks b WHERE (b.user_id=${sender} AND b.blocked_id=d.user_id) OR (b.blocked_id=${sender} AND b.user_id=d.user_id))`;
 const targets=peers.filter(p=>classId?p.class_id===classId:canAccessRoom(room,p.user_id,autoGroupScopes(p,{school:p.verified_school,grade:p.verified_grade,class_name:p.verified_class})));
 for(let i=0;i<targets.length;i+=30)await Promise.all(targets.slice(i,i+30).map(async p=>{try{if(!validSubscription(p.subscription))return;await webpush.sendNotification(p.subscription,JSON.stringify({title:'메타시간표',body:classId?'새 학급 공지가 도착했어요.':'새 메시지가 도착했어요.',url:classId?'/#home':'/#social',tag:classId?'notice-'+classId:'room-'+room.id}),{vapidDetails:{subject:'https://all-rounder-planner.vercel.app',publicKey:process.env.VAPID_PUBLIC_KEY,privateKey:process.env.VAPID_PRIVATE_KEY},TTL:3600,timeout:3000});}catch(e){if([404,410].includes(e.statusCode))await sql`DELETE FROM public.campus_push WHERE endpoint=${p.endpoint}`;else console.warn('[push]',{status:e.statusCode||503});}}));
}
