import {defaultProfile,WEEKDAYS} from './profile.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function authPage(user){
  if(user)return `<section class="panel account-panel"><h2>${esc(user.name)}님의 계정</h2><p>${esc(user.email)} · ${user.role==='admin'?'관리자':'일반 회원'}</p><p>과제와 개인 설정은 내 계정에만 저장됩니다. 관리자는 회원 수 등 운영 현황만 확인하며 다른 사람의 과제나 시간표는 열람하지 않습니다.</p>${!user.emailVerified?`<div class="alert subtle">이메일 인증을 완료하면 계정 소유를 확인할 수 있어요. 관리자 권한도 이메일 인증 후에만 적용됩니다.</div><button class="button secondary" data-action="send-code">이메일 인증번호 받기</button><form id="verify-form"><label>이메일로 받은 인증번호<input name="otp" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" required></label><button class="button primary">이메일 인증하기</button></form>`:'<p class="success-note">이메일 인증 완료 ✓</p>'}<div class="button-row"><button class="button secondary" data-action="view" data-view="settings">개인 설정</button><button class="button secondary" data-action="logout">로그아웃</button></div></section>`;
  return `<section class="panel account-panel"><span class="pill">나만의 클라우드 공간</span><h2>어디서든, 내 계획 그대로.</h2><p>회원가입하면 과제와 설정을 계정에 저장하고 다른 기기에서도 이어서 사용할 수 있어요.</p><div class="form-grid"><form id="login-form"><h3>로그인</h3><label>이메일<input name="email" type="email" autocomplete="username" required></label><label>비밀번호<input name="password" type="password" autocomplete="current-password" required></label><button class="button primary">로그인</button></form><form id="signup-form"><h3>처음이라면 회원가입</h3><label>표시 이름<input name="name" maxlength="100" autocomplete="nickname" required></label><label>이메일<input name="email" type="email" autocomplete="email" required></label><label>비밀번호<input name="password" type="password" minlength="12" maxlength="128" autocomplete="new-password" required><small>12자 이상으로 정해 주세요.</small></label><label class="checkbox-label"><input type="checkbox" required>계정 정보는 Neon 인증 서비스에, 저장한 과제·설정은 계정별 클라우드 공간에 보관됨을 확인했습니다. 학교 정보는 선택 입력입니다.</label><button class="button primary">회원가입</button></form></div><details class="source-details"><summary>비밀번호를 잊었나요?</summary><form id="reset-code-form"><label>가입한 이메일<input name="email" type="email" required></label><button class="button secondary">재설정 인증번호 받기</button></form><form id="reset-password-form"><label>이메일<input name="email" type="email" required></label><label>받은 인증번호<input name="otp" inputmode="numeric" required></label><label>새 비밀번호<input name="password" type="password" minlength="12" maxlength="128" autocomplete="new-password" required></label><button class="button primary">비밀번호 변경</button></form></details><p class="muted">로그인 전 사용하던 기록은 자동 업로드하지 않습니다. 로그인 후 직접 가져올 수 있어요. 비밀번호는 앱 저장소나 임시 초안에 보관하지 않습니다.</p><button class="text-button" data-action="demo">가입 없이 예제로 체험하기 →</button></section>`;
}
export function settingsPage(profile,onboarding=false){
  const p=profile||defaultProfile();
  return `<section class="panel"><span class="pill">${onboarding?'처음 한 번, 나에게 맞게':'언제든 바꿀 수 있어요'}</span><h2>${onboarding?'반가워요! 사용법부터 짧게 볼까요?':'개인 설정'}</h2><div class="tutorial"><article><b>01 · 공지 가져오기</b><p>문장을 붙여 넣으면 날짜·과목·분량을 해석해요.</p></article><article><b>02 · 확인 후 승인</b><p>수정 공지의 변화와 모호한 부분을 확인하세요.</p></article><article><b>03 · 내 시간에 맞게</b><p>요일별 여유 시간으로 역산하고 과부하를 알려줘요.</p></article></div><form id="settings-form"><h3>나의 기본 정보</h3><div class="form-grid">${[['name','표시 이름'],['school','학교 / 소속 (선택)'],['grade','학년 (선택)'],['className','반 (선택)']].map(([k,label])=>`<label>${label}<input name="${k}" maxlength="100" value="${esc(p[k])}" ${k==='name'?'required':''}></label>`).join('')}</div><h3>요일별 과제에 쓸 수 있는 시간</h3><p class="muted">수업·학원·식사·휴식을 제외한 시간을 분으로 입력하세요. 쉬는 날은 0분. 시간표와 중복 차감하지 않아요.</p><div class="week-inputs">${[1,2,3,4,5,6,0].map(d=>`<label>${WEEKDAYS[d]}요일<input name="capacity-${d}" aria-label="${WEEKDAYS[d]}요일 공부 시간" type="number" min="0" max="720" step="1" value="${p.weeklyMinutes[d]}" required><small>분 / 일</small></label>`).join('')}</div><h3>나의 주간 시간표 (선택)</h3><p class="muted">학교 수업이나 정기 일정을 적어 두세요. 비워 두어도 이용할 수 있어요.</p><div class="table-scroll"><table class="timetable"><thead><tr><th>교시</th>${[1,2,3,4,5].map(d=>`<th>${WEEKDAYS[d]}</th>`).join('')}</tr></thead><tbody>${Array.from({length:8},(_,i)=>`<tr><th>${i+1}</th>${Array.from({length:5},(_,d)=>`<td><input name="slot-${d}-${i}" aria-label="${WEEKDAYS[d+1]}요일 ${i+1}교시" maxlength="100" value="${esc(p.timetable[d][i])}"></td>`).join('')}</tr>`).join('')}</tbody></table></div><p class="muted">입력 중 내용은 이 탭에 임시 보관됩니다. 아래 버튼을 눌러야 개인 설정과 계획에 반영됩니다.</p><button class="button primary" type="submit">${onboarding?'설정 저장하고 시작하기':'개인 설정 저장하기'}</button></form></section>`;
}
