import {e,btn} from './campus-ui.js';
import {ROLE_NAMES,requestedRoles} from './roles.js';
const attr=(k,v)=>'data-'+k+'="'+e(v)+'"';
export function adminPage(d,error=false){
 if(!d)return '<section class="panel"><h1>관리자</h1><p>'+(error?'불러오지 못했어요.':'불러오는 중입니다.')+'</p>'+btn('다시 불러오기','admin-retry')+'</section>';
 const nav=[['users','회원·역할'],['tables','학교·반 시간표 열람'],['spaces','학급·그룹·대화 관리']].map(([k,v])=>btn(v,'admin-section',attr('section',k))).join('');
 let body='';
 if(d.section==='users')body='<p>일반 회원 '+d.memberTotal+'명 · 관리자 포함 '+d.total+'계정</p><p>비밀번호는 해시로 보관되어 관리자도 원문을 볼 수 없습니다.</p>'+d.users.map(u=>'<article class="panel"><h2>'+e(u.name)+' · '+ROLE_NAMES[u.role]+'</h2><p>'+e(u.email)+' · '+e(u.school||'소속 미설정')+' '+e(u.grade||'')+'학년 '+e(u.class_name||'')+'반</p><small>사용자 ID: '+e(u.id)+'</small>'+(u.role==='admin'?'<p>소유자 관리자 · 권한 보호됨</p>':'<form class="admin-role-form" id="admin-role-'+e(u.id)+'" data-user="'+e(u.id)+'"><label>역할<select name="role">'+requestedRoles.map(r=>'<option value="'+r+'" '+(u.role===r?'selected':'')+'>'+ROLE_NAMES[r]+'</option>').join('')+'</select></label><button class="button primary">역할 적용</button></form>')+'</article>').join('');
 if(d.section==='tables')body='<h2>학교·학년·반 시간표</h2>'+d.affiliations.map((c,i)=>btn(e(c.school)+' '+e(c.grade)+'학년 '+e(c.class_name)+'반','admin-table',attr('index',i))).join('');
 if(d.section==='spaces')body='<h2>학급</h2>'+d.classes.map(c=>'<article class="panel"><h3>'+e(c.school)+' '+e(c.grade)+'학년 '+e(c.class_name)+'반 · '+(c.closed?'폐쇄':'운영 중')+'</h3><p>담당: '+e(c.teacher||c.owner_id)+'</p>'+(!c.closed?btn('학급 편집','admin-edit-class',attr('id',c.id))+btn('학급 폐쇄','admin-mutate',attr('op','close-class')+' '+attr('id',c.id)):'')+'</article>').join('')+'<h2>그룹·모든 대화</h2><p>개인 채팅을 포함하며 열람 기록이 남습니다. 폐쇄하면 참여·전송은 차단되고 기록은 보존됩니다.</p>'+d.rooms.map(r=>'<article class="panel"><h3>'+e(r.name)+' · '+({direct:'개인 채팅',class:'학급',group:'그룹'}[r.kind])+'</h3><p>'+({approved:'운영 중',pending:'승인 대기',closed:'폐쇄'}[r.status])+' · '+r.size+'명</p>'+btn('대화·회원 열람','admin-room',attr('id',r.id))+(r.kind==='group'&&r.status!=='closed'?btn('그룹 편집','admin-edit-group',attr('id',r.id))+(r.status==='pending'?btn('개설 승인','admin-mutate',attr('op','approve-group')+' '+attr('id',r.id)):'')+btn('폐쇄·개설 반려','admin-mutate',attr('op','close-room')+' '+attr('id',r.id)):'')+'</article>').join('')+'<h2>재입장 제한</h2>'+d.exclusions.map(x=>'<p>'+e(x.name)+' · '+e(x.email)+' '+btn('제한 해제','admin-mutate',attr('op','unban')+' '+attr('id',x.scope_id)+' '+attr('user',x.user_id))+'</p>').join('');
 const end=d.section==='users'?(d.page+1)*50>=d.total:Math.max(d.rooms?.length||0,d.classes?.length||0)<100;
 return '<section class="panel"><h1>메타시간표 관리자</h1><nav class="button-row" aria-label="관리 항목">'+nav+'</nav>'+(d.section!=='tables'?'<form id="admin-search"><label>회원 이름·이메일 / 공간 이름 검색<input name="q" maxlength="100" value="'+e(d.q||'')+'"></label><button class="button primary">검색</button></form>':'')+body+(d.section!=='tables'?'<div class="button-row">'+btn('이전','admin-page',attr('page',d.page-1)+' '+(d.page<=0?'disabled':''))+'<span>'+(d.page+1)+'쪽</span>'+btn('다음','admin-page',attr('page',d.page+1)+' '+(end?'disabled':''))+'</div>':'')+'</section>';
}
export function adminMessages(d){return '<p>관리 목적으로만 열람하세요.</p><h3>참여 회원</h3>'+d.members.map(m=>'<p>'+e(m.name)+' · '+e(m.email)+' '+(d.room.kind==='direct'?'':btn('추방','admin-mutate',attr('op',d.room.kind==='class'?'kick-class':'kick-room')+' '+attr('id',d.room.class_id||d.room.id)+' '+attr('user',m.id)))+'</p>').join('')+'<h3>대화 기록</h3>'+d.messages.map(m=>'<article class="message"><small>'+e(m.name||m.sender_id)+' · '+e(m.created_at)+'</small><p>'+e(m.body)+'</p>'+(m.shared?'<p>공유 할일: '+e(m.shared.title)+'</p>':'')+'</article>').join('')+(d.next?btn('이전 대화 100개','admin-room',attr('id',d.room.id)+' '+attr('before',d.next)):'<p>이전 대화가 없습니다.</p>');}
export function adminTable(d){return '<p>조회 전용 · 날짜는 적용 주차입니다.</p>'+d.tables.map(t=>'<h3>'+e(t.week)+'</h3><div class="table-scroll"><table class="timetable"><thead><tr><th>교시</th>'+[...'월화수목금'].map(day=>'<th>'+day+'</th>').join('')+'</tr></thead><tbody>'+Array.from({length:9},(_,i)=>'<tr><th>'+(i+1)+' · '+e(d.schedule?.periodTimes?.[i]||'')+'</th>'+Array.from({length:5},(_,day)=>'<td>'+e(t.payload.table?.[day]?.[i]||'—')+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>').join('')+(d.tables.length?'':'<p>아직 저장된 시간표가 없어요.</p>');}
