import {analyze, compare, plan, FIELDS, today, addDays, validDate, validateBackup} from './engine.js';

const KEY='byeonsaeng-radar-v1';
const $=selector=>document.querySelector(selector);
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const displayDate=value=>value?`${Number(value.slice(5,7))}.${Number(value.slice(8,10))} (${['일','월','화','수','목','금','토'][new Date(value+'T12:00:00').getDay()]})`:'날짜 미정';
const fresh=()=>({version:1,tasks:[],capacity:90,acceptedPlan:null});
let data=fresh(), demo=false, realData=null, view='dashboard', draft=null, selected='', daySelected=today(), storageError='', storageLocked=false;
try { const raw=localStorage.getItem(KEY); if(raw){const parsed=JSON.parse(raw);if(!validateBackup(parsed))throw new Error('invalid');data=parsed;} }
catch {storageError='저장된 데이터를 읽지 못했습니다. 기존 저장본은 덮어쓰지 않습니다. 브라우저 설정을 확인하거나 정상 백업을 불러와 주세요.';storageLocked=true;}
const icons={radar:'◎',dashboard:'◫',notice:'≋',planner:'▦',history:'↶'};
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),4500);}
function save(){if(demo)return;if(storageLocked)return;try{localStorage.setItem(KEY,JSON.stringify(data));storageError='';}catch{storageError='브라우저에 저장하지 못했습니다. 백업 내려받기로 데이터를 보관해 주세요.';toast(storageError);}}
function invalidate(){data.acceptedPlan=null;save();}
function demoData(){
  const make=(id,title,source,minutes)=>({id,title,source,sourceDate:today(),fields:analyze(source,today()).fields,minutes,priority:2,done:false,history:[]});
  return {version:1,capacity:90,acceptedPlan:null,tasks:[
    make('demo-physics','물리 탐구 보고서',`물리 탐구 보고서\n${addDays(today(),4)} 17시까지 보고서 2쪽\n제출 방식: PDF\n장소: 물리실\n준비물: 실험 기록지\n평가 기준: 실험 근거와 결론`,120),
    make('demo-math','수학 문제 풀이',`수학 10문제\n${addDays(today(),2)} 16시까지\n제출 방식: 손글씨\n평가 기준: 풀이 과정`,120),
    make('demo-english','영어 발표 준비',`영어 발표 자료 3장\n${addDays(today(),1)} 15시까지\n제출 방식: PPT\n평가 기준: 발표 내용`,90)
  ]};
}
function changeDemo(){
  if(demo){demo=false;data=realData||fresh();realData=null;}
  else{realData=data;demo=true;data=demoData();}
  draft=null;view='dashboard';selected='';render();toast(demo?'예제 공간입니다. 내 데이터는 바뀌지 않습니다.':'내 공간으로 돌아왔습니다.');
}
function nav(){return `<aside class="sidebar"><a href="#" class="brand" data-action="home"><span class="logo">◎</span><span>변생 레이더<small>NOTICE TO PLAN</small></span></a><div class="workspace-label">나의 워크스페이스</div><nav aria-label="주 메뉴">${[['dashboard','한눈에 보기'],['notice','공지 분석'],['planner','나의 계획'],['history','변경 기록']].map(([key,label])=>`<button data-action="view" data-view="${key}" class="nav-item ${view===key?'active':''}" ${view===key?'aria-current="page"':''}><span aria-hidden="true">${icons[key]}</span>${label}${key==='notice'?'<b>＋</b>':''}</button>`).join('')}</nav><div class="sidebar-bottom"><div class="local-dot">${demo?'예제 체험 중':'이 브라우저에 저장'}</div><p>계정 없이, 공지를 외부로<br>전송하지 않고 사용할 수 있어요.</p><button class="text-button" data-action="export">백업 내려받기 ↗</button><label class="import-button" for="import">백업 불러오기<input id="import" type="file" accept=".json,application/json" hidden></label></div></aside>`;}
function heading(){const titles={dashboard:['한눈에 보기','바뀐 공지부터 오늘의 할 일까지.'],notice:['공지 분석','원문을 남기고, 바뀐 내용만 확인하세요.'],planner:['나의 계획','마감 전에 끝낼 수 있도록 시간을 나눠요.'],history:['변경 기록','어떤 공지에서 무엇이 달라졌는지 되짚어요.']};return `<header class="page-heading"><div><div class="eyebrow">${displayDate(today())} · ${demo?'예제 워크스페이스':'MY WORKSPACE'}</div><h1>${titles[view][0]}</h1><p>${titles[view][1]}</p></div><button class="button secondary" data-action="demo">${demo?'내 공간으로 돌아가기':'예제로 체험하기'} <span aria-hidden="true">↗</span></button></header>`;}
function summary(){const p=plan(data.tasks,data.capacity),active=data.tasks.filter(t=>!t.done);return `<div class="stats"><article><span>진행 중인 과제</span><strong>${active.length}<small>개</small></strong><p>완료한 과제 ${data.tasks.length-active.length}개</p></article><article class="${p.totalShortage?'stat-warning':''}"><span>14일 계획 · 배치하지 못한 시간</span><strong>${p.totalShortage}<small>분</small></strong><p>${p.totalShortage?'가용 시간이나 마감을 조정해 주세요':'현재 추정 시간으로 배치 가능해요'}</p></article><article><span>마감일 확인 필요</span><strong>${p.missing.length}<small>개</small></strong><p>날짜가 없으면 계획에 포함되지 않아요</p></article></div>`;}
function graph(p){return `<div class="graph" aria-label="앞으로 7일의 계획된 작업 시간">${p.days.slice(0,7).map(d=>`<button class="day-bar ${d.date===daySelected?'chosen':''}" data-action="day" data-date="${d.date}" aria-label="${displayDate(d.date)} ${d.used}분, 가용 ${d.capacity}분"><span>${d.used}<small>분</small></span><span class="bar-track"><span style="height:${Math.round(d.used/Math.max(1,d.capacity)*100)}%"></span></span><b>${d.date===today()?'오늘':displayDate(d.date).split(' ')[0]}</b></button>`).join('')}</div>`;}
function tasksPanel(){return `<section class="panel"><div class="panel-heading"><h2>진행 중인 과제 <span class="count">${data.tasks.filter(t=>!t.done).length}</span></h2><button class="text-button" data-action="new">＋ 과제 등록</button></div>${data.tasks.length?`<div class="task-list">${data.tasks.map(t=>`<article class="task ${t.done?'done':''}"><button class="check-task" data-action="done" data-id="${esc(t.id)}" aria-label="${esc(t.title)} ${t.done?'완료 취소':'완료'}" aria-pressed="${t.done}">${t.done?'✓':''}</button><div class="task-main"><span class="subject">${esc(t.fields.subject||'미분류')}</span><h3>${esc(t.title)}</h3><p>${displayDate(t.fields.due)}${t.fields.time?' '+esc(t.fields.time):''} · 남은 작업 ${t.minutes}분${t.fields.due&&t.fields.due<today()&&!t.done?' · 마감 지남':''}</p></div><button class="icon-button" data-action="edit" data-id="${esc(t.id)}" aria-label="${esc(t.title)} 수정">수정</button><button class="icon-button" data-action="revise" data-id="${esc(t.id)}" aria-label="${esc(t.title)} 수정 공지 비교">공지 비교 ↗</button></article>`).join('')}</div>`:`<div class="empty"><span class="empty-icon">＋</span><h3>첫 번째 공지를 가져와 보세요</h3><p>“내일 물리 보고서 2쪽”처럼 짧게 입력해도 좋아요.<br>등록하기 전에 해석된 내용을 확인할 수 있어요.</p><button class="button primary" data-action="new">공지로 과제 등록</button></div>`}</section>`;}
function dashboard(){const p=plan(data.tasks,data.capacity);return `${summary()}<div class="dashboard-grid"><section class="feature-card"><span class="pill">변화 → 영향 → 계획</span><h2>공지 하나가 바뀌면,<br>내 계획도 달라지니까.</h2><p>수정 공지와 기존 과제를 연결하고<br>마감·분량·준비물의 변화를 확인하세요.</p><button class="button lime" data-action="${demo?'sample-revision':'open-revision'}">${demo?'물리 수정 공지 비교하기':'수정 공지 가져오기'} <span>↗</span></button><div class="feature-foot">${demo?'예제: 목요일 2쪽 → 화요일 4쪽에 해당하는 날짜 변화':'변경 내용은 직접 승인한 뒤에만 반영돼요.'}</div></section><section class="panel week-panel"><div class="panel-heading"><h2>이번 주 작업량</h2><button class="text-button" data-action="view" data-view="planner">계획 보기 ↗</button></div><p class="muted">하루 ${data.capacity}분 기준 · 역산 배치 미리보기</p>${graph(p)}<div class="legend"><i></i> 배치한 시간 <span>막대 전체 = 하루 가용 시간</span></div></section></div>${tasksPanel()}`;}
function sourceForm(){const task=data.tasks.find(t=>t.id===selected);return `<section class="panel"><div class="panel-heading"><h2>분석할 공지</h2><span class="pill neutral">외부 전송 없음</span></div><form id="source-form"><div class="form-grid"><label>연결할 과제<select name="task" id="task-select"><option value="">새 과제로 등록</option>${data.tasks.map(t=>`<option value="${esc(t.id)}" ${t.id===selected?'selected':''}>${esc(t.title)}</option>`).join('')}</select></label><label>이 공지가 작성된 날짜<input type="date" name="sourceDate" value="${today()}" required><small>‘내일’, ‘다음 주’는 이 날짜를 기준으로 해석해요.</small></label></div><label>공지 내용<textarea name="source" id="notice-text" rows="7" maxlength="12000" required placeholder="예: 내일 물리 보고서 2쪽, 17시까지 PDF 제출&#10;장소: 물리실&#10;준비물: 실험 기록지"></textarea></label>${task?`<details class="source-details"><summary>저장된 원문 보기 · ${displayDate(task.sourceDate)}</summary><pre>${esc(task.source)}</pre></details>`:''}<div class="form-bottom"><p>날짜·분량은 문장에서, 준비물·대상은 ‘준비물: …’처럼 읽어요.</p><button class="button primary" type="submit">${task?'변경점 분석하기':'과제 내용 분석하기'} →</button></div></form></section><div class="notice-help"><strong>자동 해석은 초안이에요.</strong> 이 버전은 한국어 표현 규칙을 사용합니다. 모든 문장을 이해하는 AI가 아니며, 여러 날짜나 미정 표현은 확인 대상으로 남겨요. 메신저나 외부 사이트의 공지를 자동으로 수집하지 않습니다.</div>`;}
function diffPanel(){if(!draft?.old)return '';const changes=compare({fields:draft.old.fields,evidence:analyze(draft.old.source,draft.old.sourceDate).evidence},draft.analysis);return `<section class="panel"><div class="panel-heading"><h2>달라진 내용</h2><span class="pill">${changes.length}개 항목 확인</span></div>${changes.length?`<div class="diff-list">${changes.map(c=>`<article class="diff-item"><div><strong>${c.label}</strong><span class="pill ${c.kind==='확인 필요'?'warning':''}">${c.kind}</span></div><div class="diff-values"><span>${esc(c.before||'확정 값 없음')}</span><span aria-hidden="true">→</span><strong>${esc(c.after||'새 공지에서 확정할 수 없음')}</strong></div><details><summary>원문 표현 확인</summary><p>이전: ${esc(c.oldEvidence)}</p><p>수정: ${esc(c.newEvidence)}</p></details>${c.before&&!c.after?'<p class="warning-text">표현이 빠졌다고 취소된 것은 아니에요. 아래에는 기존 값을 남겨 두었으니 유지할지 지울지 확인하세요.</p>':''}</article>`).join('')}</div>`:'<p class="muted">구조화한 항목의 변화는 없습니다. 아래 원문에서 다른 내용도 확인해 주세요.</p>'}<details class="source-details"><summary>전체 원문 비교</summary><div class="form-grid"><pre>${esc(draft.old.source)}</pre><pre>${esc(draft.source)}</pre></div></details></section>`;}
function reviewForm(){if(!draft)return '';const a=draft.analysis; const effective=draft.old?{...draft.old.fields}:{};for(const key of Object.keys(FIELDS))if(a.fields[key])effective[key]=a.fields[key];
  if(draft.edit)Object.assign(effective,draft.old.fields);
  const title=draft.old?.title||draft.source.split('\n')[0].slice(0,100);
  return `<div id="review">${diffPanel()}<div class="review-grid"><section class="panel"><div class="panel-heading"><h2>확인하고 ${draft.old?'수정':'등록'}하기</h2><span class="step">최종 승인</span></div><form id="review-form"><label>과제 이름<input name="title" maxlength="200" value="${esc(title)}" required></label><div class="form-grid">${Object.entries(FIELDS).map(([key,label])=>`<label>${label}${key==='due'?' <small>미정이면 비워 두세요</small>':''}<input name="${key}" type="${key==='due'?'date':key==='time'?'time':'text'}" maxlength="1000" value="${esc(effective[key]||'')}" placeholder="확인 필요"></label>`).join('')}<label>남은 작업 시간 (분)<input name="minutes" type="number" min="0" max="10080" step="5" value="${draft.old?.minutes??60}" required><small>분량 증가만으로 자동 변경하지 않아요.</small></label><label>중요도<select name="priority">${[[1,'보통'],[2,'중요'],[3,'매우 중요']].map(([value,text])=>`<option value="${value}" ${(draft.old?.priority??2)===value?'selected':''}>${text}</option>`).join('')}</select></label></div><label class="checkbox-label"><input name="acknowledged" type="checkbox" required>원문과 해석 결과를 확인했습니다. 미정인 정보는 확인 후 수정하겠습니다.</label><div class="button-row"><button class="button primary" type="submit">${draft.old?'변경 승인하고 계획 재계산':'과제 등록하고 계획 보기'}</button><button class="button secondary" type="button" data-action="cancel-draft">취소</button></div></form></section><aside class="review-aside"><section class="panel warning-panel"><h2>확인이 필요한 부분</h2>${a.issues.length?`<ul>${a.issues.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'<p>규칙으로 발견한 충돌은 없어요. 원문과 최종 값은 한 번 더 확인해 주세요.</p>'}<h3>물어볼 질문 초안</h3><ul>${a.questions.map(q=>`<li>${esc(q)}</li>`).join('')||'<li>기본 항목이 채워져 있습니다. 추가 조건도 원문에서 확인해 주세요.</li>'}</ul><button class="button secondary" data-action="copy-questions">질문 복사</button><p class="muted">자동으로 메시지를 보내지 않아요.</p></section><section class="panel"><h3>계획에 반영되는 것</h3><p>마감일·남은 작업 시간·중요도가 바뀌면 14일 계획을 다시 계산합니다.</p><p class="muted">시간을 초과하면 과제를 숨기지 않고 배치하지 못한 분량을 표시해요.</p></section></aside></div></div>`;
}
function notice(){return `${sourceForm()}${reviewForm()}`;}
function planner(){const p=plan(data.tasks,data.capacity),day=p.days.find(d=>d.date===daySelected)||p.days[0];return `<div class="plan-controls panel"><label>하루에 쓸 수 있는 시간 <span class="capacity-input"><input id="capacity" type="number" min="15" max="720" step="15" value="${data.capacity}"> 분</span></label><p>수업·식사·휴식 시간을 뺀 시간을 입력하세요.<br>앞으로 14일, 마감 당일까지 작업할 수 있다고 가정해요.</p><button class="button primary" data-action="approve-plan" ${data.tasks.some(t=>!t.done)?'':'disabled'}>${data.acceptedPlan?'계획 승인됨 ✓':'이 계획 승인하기'}</button></div>${p.totalShortage?`<div class="alert"><strong>${p.totalShortage}분을 배치하지 못했어요.</strong> 하루 가용 시간을 늘리거나, 남은 작업량·마감을 확인해 주세요. 계획을 승인해도 부족한 작업이 해결되지는 않습니다.</div>`:''}${p.missing.length?`<div class="alert subtle">마감일이 없는 과제 ${p.missing.length}개는 계산에서 제외했어요.</div>`:''}<div class="planner-grid"><section class="panel"><div class="panel-heading"><h2>${data.acceptedPlan?'승인한 계획':'역산 계획 미리보기'}</h2><span class="pill neutral">14일</span></div><p class="muted">빠른 마감부터 시간을 확보하고, 각 과제는 마감일부터 거꾸로 배치해요. 같은 마감에서는 중요도를 먼저 봐요.</p><div class="calendar-grid">${p.days.map(d=>`<button class="calendar-day ${d.date===day.date?'selected':''}" data-action="day" data-date="${d.date}" aria-pressed="${d.date===day.date}"><span>${displayDate(d.date)}</span><strong>${d.used}<small> / ${d.capacity}분</small></strong><i style="--fill:${d.used/Math.max(1,d.capacity)*100}%"></i><small>${d.items.length?`${d.items.length}개 과제`:'여유 시간'}</small></button>`).join('')}</div></section><section class="panel day-detail"><span class="eyebrow">DAY PLAN</span><h2>${displayDate(day.date)} 할 일</h2>${day.items.map(x=>`<article class="session"><span class="session-dot"></span><div><h3>${esc(x.title)}</h3><p>${x.minutes}분 작업</p></div></article>`).join('')||'<p class="muted">배치된 작업이 없어요.</p>'}<div class="day-total">남는 시간 <strong>${day.capacity-day.used}분</strong></div>${p.overflow.length?`<h3 class="warning-text">배치하지 못한 작업</h3>${p.overflow.map(x=>`<p>${esc(data.tasks.find(t=>t.id===x.id)?.title)}<br><strong>${x.minutes}분</strong> · ${x.reason}</p>`).join('')}`:''}<p class="muted">하루 단위 추정 계획이에요. 마감 시각 이전의 실제 여유 시간은 직접 확인하세요. 14일 이후 마감 과제는 아직 배치하지 않아요.</p></section></div>`;}
function history(){return `<section class="panel"><div class="panel-heading"><h2>과제별 원문과 수정 이력</h2><span class="pill neutral">이 브라우저에 보관</span></div>${data.tasks.length?data.tasks.map(t=>`<details class="history-item"><summary><span>${esc(t.title)}</span><small>${t.history.length}번 수정 · 현재 ${displayDate(t.fields.due)}</small></summary><h3>현재 원문 · 작성일 ${displayDate(t.sourceDate)}</h3><pre>${esc(t.source)}</pre>${t.history.slice().reverse().map((h,i)=>`<div class="version"><strong>이전 버전 ${t.history.length-i}</strong><p class="muted">보관 시각 ${esc(h.at)} · 원문 작성일 ${displayDate(h.sourceDate)}</p><pre>${esc(h.source)}</pre>${h.fields?`<p>당시 확인한 마감: ${esc(h.fields.due||'미정')} · 남은 작업 ${esc(h.minutes)}분</p>`:''}</div>`).join('')}<button class="button danger" data-action="delete" data-id="${esc(t.id)}">이 과제 삭제</button></details>`).join(''):'<div class="empty"><h3>아직 변경 기록이 없어요</h3><p>공지를 등록하고 수정하면 이전 원문이 여기에 남아요.</p></div>'}</section>`;}
function render(){
  $('#app').innerHTML=`${nav()}<div class="workspace"><div class="topbar"><span>바뀐 정보를, 놓치지 않는 계획으로.</span><span class="status-chip">${demo?'DEMO · 실제 데이터와 분리':'LOCAL · 나만의 공간'}</span></div><main id="main">${heading()}${storageError?`<div class="alert" role="alert">${esc(storageError)}</div>`:''}${demo?'<div class="demo-banner">예제 체험 중 · 예제를 수정해도 내 데이터는 바뀌지 않아요.</div>':''}${({dashboard,notice,planner,history}[view])()}<footer>변생 레이더 · 규칙 기반 해석 / 외부 AI 전송 없음 <span>브라우저 데이터 삭제 시 기록도 사라집니다. 백업을 보관해 주세요.</span></footer></main></div>`;
  if(view==='notice'&&draft){$('#notice-text').value=draft.source;$('#source-form [name="sourceDate"]').value=draft.sourceDate;}
}
function openRevision(id){selected=id||data.tasks.find(t=>!t.done)?.id||'';draft=null;view='notice';render();window.scrollTo(0,0);if(!selected)toast('먼저 원본 공지를 등록해 주세요.');}
document.addEventListener('submit',event=>{
  if(event.target.id==='source-form'){
    event.preventDefault();const f=new FormData(event.target),source=String(f.get('source')).trim(),sourceDate=String(f.get('sourceDate'));
    if(!source)return toast('공지 내용을 입력해 주세요.');if(data.tasks.length>=300&&!f.get('task'))return toast('최대 300개까지 보관할 수 있어요.');
    const old=data.tasks.find(t=>t.id===f.get('task'));
    if(old&&old.source===source&&old.sourceDate===sourceDate)return toast('저장된 공지와 같습니다. 과제 내용 수정은 한눈에 보기의 수정 버튼을 이용하세요.');
    draft={source,sourceDate,analysis:analyze(source,sourceDate),old};selected=old?.id||'';render();$('#review')?.scrollIntoView({behavior:'smooth',block:'start'});
  }
  if(event.target.id==='review-form'){
    event.preventDefault();const f=new FormData(event.target);const title=String(f.get('title')).trim();if(!title)return toast('과제 이름을 입력해 주세요.');
    const fields=Object.fromEntries(Object.keys(FIELDS).map(k=>[k,String(f.get(k)||'').trim()||null]));
    if(fields.due&&!validDate(fields.due))return toast('마감 날짜를 확인해 주세요.');
    const minutes=Number(f.get('minutes')),priority=Number(f.get('priority'));if(!Number.isFinite(minutes)||minutes<0||minutes>10080)return toast('남은 작업 시간을 확인해 주세요.');
    const before=plan(data.tasks,data.capacity).totalShortage;
    const task={id:draft.old?.id||crypto.randomUUID(),title,source:draft.source,sourceDate:draft.sourceDate,fields,minutes,priority,done:draft.old?.done||false,history:draft.old?[...draft.old.history,{source:draft.old.source,sourceDate:draft.old.sourceDate,fields:draft.old.fields,minutes:draft.old.minutes,at:new Date().toLocaleString('ko-KR')}].slice(-100):[]};
    if(draft.old)data.tasks=data.tasks.map(t=>t.id===task.id?task:t);else data.tasks.push(task);
    invalidate();draft=null;view='planner';render();window.scrollTo(0,0);const after=plan(data.tasks,data.capacity).totalShortage;
    toast(`저장했어요. 배치하지 못한 시간: ${before}분 → ${after}분`);
  }
});
document.addEventListener('change',event=>{
  if(event.target.id==='task-select'){const text=$('#notice-text').value,sourceDate=$('#source-form [name="sourceDate"]').value;selected=event.target.value;draft=null;render();$('#notice-text').value=text;$('#source-form [name="sourceDate"]').value=sourceDate;}
  if(event.target.id==='capacity'){const n=Number(event.target.value);if(!Number.isFinite(n)||n<15||n>720||n%15){event.target.value=data.capacity;return toast('15~720분 사이에서 15분 단위로 입력해 주세요.');}data.capacity=n;invalidate();render();}
  if(event.target.id==='import'){
    const file=event.target.files[0];if(!file)return;if(file.size>5_000_000)return toast('5MB 이하의 백업만 불러올 수 있어요.');
    file.text().then(text=>{const imported=JSON.parse(text);if(!validateBackup(imported))throw new Error();if(!confirm(`${demo?'예제':'현재'} 공간의 과제 ${data.tasks.length}개를 백업 내용으로 교체할까요? 먼저 백업을 내려받는 것을 권장합니다.`))return;data={version:1,tasks:imported.tasks,capacity:imported.capacity,acceptedPlan:null};storageLocked=false;save();draft=null;selected='';view='dashboard';render();toast('백업을 불러왔어요.');}).catch(()=>toast('올바른 변생 레이더 백업 파일이 아닙니다. 현재 데이터는 그대로예요.'));
  }
});
document.addEventListener('click',async event=>{
  const button=event.target.closest('[data-action]');if(!button)return;event.preventDefault();const {action,id}=button.dataset;
  if(action==='view'||action==='home'){view=action==='home'?'dashboard':button.dataset.view;render();window.scrollTo(0,0);}
  if(action==='demo')changeDemo();
  if(action==='new'){selected='';draft=null;view='notice';render();window.scrollTo(0,0);$('#notice-text').focus();}
  if(action==='open-revision'||action==='revise')openRevision(id);
  if(action==='sample-revision'){openRevision('demo-physics');$('#notice-text').value=`물리 탐구 보고서\n${addDays(today(),2)} 17시까지 보고서 4쪽\n제출 방식: PDF\n장소: 물리실\n준비물: 실험 기록지, 그래프\n평가 기준: 실험 근거와 결론`;toast('수정 공지를 채웠어요. 분석 후 남은 작업 시간을 240분으로 바꿔 비교해 보세요.');}
  if(action==='edit'){const old=data.tasks.find(t=>t.id===id);draft={old,edit:true,source:old.source,sourceDate:old.sourceDate,analysis:analyze(old.source,old.sourceDate)};selected=id;view='notice';render();$('#review').scrollIntoView({behavior:'smooth'});}
  if(action==='done'){const task=data.tasks.find(t=>t.id===id);task.done=!task.done;invalidate();render();}
  if(action==='day'){daySelected=button.dataset.date;view='planner';render();}
  if(action==='approve-plan'){data.acceptedPlan={at:new Date().toISOString(),start:today()};save();render();toast('계획을 승인했어요. 과제나 가용 시간을 바꾸면 다시 확인받습니다.');}
  if(action==='cancel-draft'){draft=null;render();}
  if(action==='copy-questions'){const text=[...draft.analysis.issues,...draft.analysis.questions].join('\n');try{await navigator.clipboard.writeText(text);toast('질문을 복사했어요.');}catch{toast('복사 권한이 없습니다. 화면의 질문을 선택해서 복사해 주세요.');}}
  if(action==='delete'){const task=data.tasks.find(t=>t.id===id);if(confirm(`‘${task.title}’와 변경 이력을 삭제할까요? 앱에서는 되돌릴 수 없으며, 저장한 백업으로 복원할 수 있습니다.`)){data.tasks=data.tasks.filter(t=>t.id!==id);invalidate();render();toast('과제와 변경 이력을 삭제했어요.');}}
  if(action==='export'){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`byeonsaeng-${demo?'demo-':''}${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);toast('백업에는 공지 원문이 포함돼요. 안전하게 보관하세요.');}
});
window.addEventListener('storage',event=>{if(event.key===KEY&&!demo){storageLocked=true;storageError='다른 탭에서 저장 내용이 바뀌었어요. 충돌을 막기 위해 이 탭의 저장을 멈췄습니다. 새로고침 후 이어서 사용하세요.';render();}});
if(data.acceptedPlan?.start!==today())data.acceptedPlan=null;
render();
