import {feedback,formFeedback,dismissFeedback} from './feedback-ui.js';
import {lessonDeadline} from './lesson-deadline.js';
import {enablePush,disablePush} from './push-client.js';
import {subjectsFrom} from './entry-recognition.js';
import {parseBatch} from './quick-entry.js';
import {ROLE_NAMES,effectiveRole,canPublish} from './roles.js';
import {adminPage,adminMessages,adminTable} from './admin-ui.js';
import {scheduleEditor,scheduleRows,fillSchedule} from './schedule-ui.js';
import {sciencePreset,scheduleFromFields,scheduleFor,currentLesson,defaultSchedule} from './day-schedule.js';
import {cloud,loadCloud,queueSave,retrySave,authAction,signOut,api} from './cloud.js';
import {authPage} from './account-ui.js';
import {upgrade,validProfile} from './profile.js';
import {plan,today,iso,addDays,validateBackup,validDate} from './engine.js';
import {parseEntry,TYPES,PERIODS,sunday,moveMonth,normalizedRange,weekPlan,emptyTable,tableFor,typeOf} from './campus-model.js';
import {createQuickTask} from './quick-entry.js';
import {commitEntries,removeTask} from './campus-entry.js';
import {inspectNotice,applyNoticeRows} from './notice-intake.js';
import {remainingMinutes,dailyCapacity,recordStudy} from './workload.js';
import {finishBy,deadlineStamp} from './live-time.js';
import {applyAppearance,PALETTES,validAppearance,validReminders,defaultReminders,scheduledReminderSlots} from './preferences.js';
import {appearancePanel} from './preferences-ui.js';
import {remindersPanel,enableReminders,showReminder,calendarFile} from './reminders.js';
import {e,btn,dayLabel,entryOptions,entryPage,homePage,plannerPage,socialPage,tutorPage,messagesHtml,taskLine,selectedHomeTasks} from './campus-ui.js';
const adminRoute=location.pathname.replace(/\/$/,'')==='/admin';
const $=q=>document.querySelector(q),pages={home:['⌂','메인'],entry:['＋','할일 추가'],planner:['▦','주간 계획'],tutor:['✧','공부 도우미'],social:['☏','소통'],settings:['⚙','설정'],admin:['⚿','관리자']};
const s={data:null,userId:null,community:{member:null,person:null,people:[],notices:[],rooms:[],applications:[]},classTables:{},homeWeek:sunday(today()),entryWeek:sunday(today()),planWeek:sunday(today()),homeMonth:today(),entryMonth:today(),entries:[],entryIndex:0,entryText:'',editId:null,forms:{},room:null,messages:[],tutor:{enabled:false,subject:'수학',mode:'concept',question:'',image:null,result:null,revealed:1},meals:'급식 연결을 확인하고 있어요.'};
const role=()=>s.community.role||effectiveRole(cloud.user,s.community.person,s.community.member);
const visiblePages=()=>Object.entries(pages).filter(([v])=>v==='admin'?false:role()==='teacher'?!['entry','planner','tutor'].includes(v):true);
const logo='<span class="restored-logo"><svg viewBox="0 0 32 32" width="32" height="32" aria-hidden="true"><rect x="5" y="7" width="22" height="21" rx="5" fill="none" stroke="currentColor" stroke-width="2.2"/><path d="M10 4v6m12-6v6M5 14h22M10 23v-5l6 5 6-5v5" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"/></svg></span>';
let schedulePhoto=null,schoolTimer,schoolRequest=0,polling=false;
const subjectList=()=>subjectsFrom(s.data.profile,s.classTables[s.entryWeek]);
const resolveEntry=d=>lessonDeadline(d,s.data.profile,s.classTables,today());
const entryParse=(text,base=today())=>resolveEntry(parseEntry(text,base,subjectList()));
const schoolURL=(p,week)=>'/api/school?school='+encodeURIComponent(p.school)+'&grade='+encodeURIComponent(p.grade)+'&className='+encodeURIComponent(p.className)+'&week='+week;
async function getSchool(p=s.data.profile,week=s.homeWeek){if(!p.school?.trim())return null;return api(schoolURL(p,week));}
async function checkSchool(){const f=$('#profile-form');if(!f)return;const v=fd(f),ticket=++schoolRequest;try{const r=await getSchool({school:v.school?.trim(),grade:v.grade?.trim(),className:v.className?.trim()});if(ticket!==schoolRequest||!f.isConnected)return;s.school=r;s.schoolKey=[v.school,v.grade,v.className].map(x=>x?.trim()||'').join('|');const box=f.querySelector('#school-state');if(box)box.textContent=r?.schedule?'등록된 학교 일과를 불러왔어요. '+(r.table?'같은 반 시간표도 함께 적용됩니다.':'과목만 입력해 주세요.'):'이 학교의 첫 등록이에요. 사진을 읽고 시각을 확인하거나 직접 작성하세요.';if(r?.schedule){const config={...r.schedule,table:r.table?.table||s.data.profile.timetable.map(d=>Array.from({length:9},(_,i)=>d[i]||''))};fillSchedule(f,config);const timing=f.querySelector('.schedule-editor details');if(timing)timing.hidden=true;f.querySelectorAll('[data-action=analyze-schedule],[data-action=science-preset],#schedule-photo').forEach(el=>el.disabled=true);f.querySelectorAll('[name^=slot-]').forEach(el=>el.readOnly=!!r.table);}else{f.querySelectorAll('[name^=slot-]').forEach(el=>el.readOnly=false);f.querySelectorAll('[data-action=analyze-schedule],[data-action=science-preset],#schedule-photo').forEach(el=>el.disabled=false);const details=f.querySelector('.schedule-editor details');if(details)details.hidden=false;}capture();}catch(err){error(err);}}
async function sharedSetup(){try{const p=s.data.profile,r=await getSchool(p);s.school=r;if(!r?.schedule){await api('/api/school',{method:'POST',body:JSON.stringify({action:'schedule',daySchedule:p.daySchedule||defaultSchedule(p.periodTimes),periodTimes:p.periodTimes||PERIODS})});}if(!r?.table)await api('/api/school',{method:'POST',body:JSON.stringify({action:'table',week:s.homeWeek,table:p.timetable.map(d=>Array.from({length:9},(_,i)=>d[i]||''))})});s.classTables={};}catch(err){if(err.status!==409)throw err;s.school=await getSchool();s.classTables={};toast('먼저 등록된 학교·학급 시간표를 적용했어요.');}}

let booting=true,view='home',drag=null,minute='',noticeTimer,saveTimer;
const openedDetails=new Set();
document.addEventListener('toggle',event=>{const d=event.target;if(d.tagName!=='DETAILS'||!d.isConnected)return;const key=view+':'+d.querySelector('summary')?.textContent;d.open?openedDetails.add(key):openedDetails.delete(key);},true);
const toast=text=>feedback(text,'info');
const error=err=>feedback(err.message||'요청을 처리하지 못했습니다. 다시 시도해 주세요.','error');
cloud.onFeedback=feedback;
const inflight=new Set();
const fd=f=>Object.fromEntries(new FormData(f));
function persist(){if(!cloud.user)return;try{sessionStorage.setItem('campus-draft-'+cloud.user.id,JSON.stringify({forms:s.forms,entries:s.entries,entryIndex:s.entryIndex,entryText:s.entryText,editId:s.editId}));}catch{toast('초안 임시 저장이 어려워요. 입력 내용을 복사해 주세요.');}}
function capture(){if(!cloud.user)return;for(const f of document.querySelectorAll('form')){if(['tutor-form','entry-form'].includes(f.id))continue;if(f.querySelector('[type=password]'))continue;const pending=s.forms[f.id];s.forms[f.id]=fd(f);if(pending?.clientId)Object.assign(s.forms[f.id],{clientId:pending.clientId,fingerprint:pending.fingerprint});for(const c of f.querySelectorAll('[type=checkbox]'))s.forms[f.id][c.name]=c.checked;}captureEntry();persist();}
function restore(){for(const[id,values]of Object.entries(s.forms)){const f=document.getElementById(id);if(!f)continue;if(f.querySelector('.schedule-rows')){const rows=[];for(let i=0;i<30&&Object.hasOwn(values,'schedule-label-'+i);i++)rows.push({label:values['schedule-label-'+i],start:values['schedule-start-'+i],end:values['schedule-end-'+i],period:values['schedule-period-'+i],days:String(values['schedule-days-'+i]||'').split(','),examOnly:!!values['schedule-exam-'+i]});if(rows.length)f.querySelector('.schedule-rows').innerHTML=scheduleRows(rows);}for(const[k,v]of Object.entries(values)){const el=f.elements.namedItem(k);if(!el||!el.tagName||el.type==='file')continue;if(el.type==='checkbox')el.checked=!!v;else el.value=v;}}}
function captureEntry(){const f=$('#entry-form'),d=s.entries[s.entryIndex];if(!f||!d||!f.elements.title)return;const v=fd(f);Object.assign(d,{title:v.title,taskType:v.taskType,category:['study','bring','buy','other'].includes(v.taskType)?v.taskType:'assignment',totalMinutes:Number(v.minutes),durationRequired:!v.minutes,minutesEstimated:!v.minutes,priority:Number(v.priority),difficulty:Number(v.difficulty),note:v.note||'',completedMinutes:Number(v.completedMinutes||0),startDate:v.startDate||null});Object.assign(d.fields,{subject:v.subject||null,due:v.due||null,time:v.time||null});}
function capacity(){const now=Date.now(),spent=s.data.tasks.reduce((sum,t)=>sum+(t.studyLog||[]).filter(l=>iso(new Date(l.at))===today()).reduce((n,l)=>n+l.minutes,0),0);return {condition:s.data.profile.conditions?.[today()]||'middle',weekly:s.data.profile.weeklyMinutes,overrides:s.data.profile.dateOverrides||{},today:today(),now,spent};}
function save(){if(!cloud.user)throw new Error('로그인이 필요해요.');if(cloud.locked)throw new Error('저장이 잠겼어요. 백업 후 새로고침해 주세요.');if(!validateBackup(s.data))throw new Error('날짜·시간·입력 범위를 확인해 주세요.');s.data.acceptedPlan=null;queueSave(s.data);}
async function saved(){const end=Date.now()+20000;while(cloud.running||cloud.pending){if(cloud.locked||/실패|충돌|만료/.test(cloud.status)||Date.now()>end)throw new Error('저장에 실패했습니다. 입력 내용은 이 탭에 남아 있습니다. 저장 상태와 연결을 확인한 뒤 다시 시도해 주세요.');await new Promise(r=>setTimeout(r,200));}}
async function campus(action,body={}){return api('/api/campus',{method:'POST',body:JSON.stringify({action,...body})});}
async function refreshCommunity(){const id=cloud.user?.id;if(!id)return;try{const c=await api('/api/campus');if(cloud.user?.id===id){s.community=c;if(s.room&&!c.rooms.some(r=>r.id===s.room.id)){s.room=null;s.messages=[];delete s.forms['message-form'];}}}catch(err){toast('학급 연결: '+err.message);}}
async function loadTable(week){if(!cloud.user||Object.hasOwn(s.classTables,week))return;const id=cloud.user.id;s.classTables[week]=null;try{const shared=await getSchool(s.data.profile,week),verified=s.community.member?(await api('/api/campus?week='+week)).table:null;if(cloud.user?.id!==id)return;s.school=shared;s.classTables[week]={...(verified||{}),...(shared?.table||{}),...(shared?.schedule||{})};if(!s.classTables[week].table)delete s.classTables[week].table;if(['home','entry'].includes(view)){capture();render();}}catch(err){delete s.classTables[week];error(err);}}
function go(next){if(!pages[next])next='home';if(!visiblePages().some(([v])=>v===next))next='home';view=next;if(location.hash!=='#'+next)location.hash=next;render();window.scrollTo(0,0);}
function authScreen(){if(adminRoute)return '<main class="login-shell"><h1>메타시간표 관리자 로그인</h1><p>기존 관리자 계정으로 로그인하세요. 추가 인증은 없습니다.</p><form id="login-form"><label>이메일<input name="email" type="email" autocomplete="username" required></label><label>비밀번호<input name="password" type="password" autocomplete="current-password" required></label><button class="button primary">로그인</button></form><a href="/">일반 사용자 페이지</a></main>';return `<main class="login-shell"><a class="login-brand" href="#home">${logo} 메타시간표</a><h1>시간을 아끼다, 메타시간표</h1><p>로그인하면 나만의 계획과 학교 소식을 한곳에서 볼 수 있어요.</p>${authPage(null).replace(/<button class="text-button" data-action="demo">.*?<\/button>/,'').replace('학교 정보는 선택 입력입니다.','처음 로그인하면 학교·학년·반과 일일 시간을 입력합니다.').replace('로그인 전 사용하던 기록은 자동 업로드하지 않습니다. 로그인 후 직접 가져올 수 있어요.','이전 버전의 로그인 전 기록은 설정에서 직접 가져올 수 있어요.')}</main>`;}
function settings(){const p=s.data.profile,c=s.community;return `<section class="panel"><h1>${p.campusOnboarded?'나의 설정':'처음 한 번, 나에게 맞게'}</h1><p>한 줄 입력 → 옵션 확인 → 추가하기. 선생님이 없어도 개인 모드로 쓸 수 있어요.</p><form id="profile-form"><div class="form-grid">${[['name','표시 이름'],['school','학교 이름 (정확히)'],['grade','학년'],['className','반']].map(([k,l])=>`<label>${l}<input name="${k}" maxlength="100" required value="${e(p[k])}"></label>`).join('')}</div><p class="muted">같은 학교는 일과 시각, 같은 반은 과목 시간표를 공유해요. 학급은 선생님 개설 후 같은 소속만 코드 없이 입장해요. 그룹은 승인 후 직접 입장해요.</p><h2>요일별 일일 시간</h2><div class="week-inputs">${[0,1,2,3,4,5,6].map(d=>`<label>${'일월화수목금토'[d]}<input name="capacity-${d}" type="number" min="0" max="720" required value="${p.weeklyMinutes[d]}"><small>분</small></label>`).join('')}</div><label class="checkbox-label"><input name="discoverable" type="checkbox" ${c.person?.discoverable?'checked':''}>같은 학교 사용자에게 표시 이름·학년·반을 공개하고 개인 채팅을 받겠습니다. 자동으로 그룹에 가입하지 않습니다.</label><p>현재 역할: ${ROLE_NAMES[role()]} · 역할은 관리자가 지정합니다.</p>${!p.campusOnboarded?'<p id="school-state" role="status">학교 이름을 입력하면 공통 일과를 확인해요.</p>'+scheduleEditor(p,s.homeWeek):(!c.member||['teacher','admin'].includes(role())?btn('시간표·야자 일과 편집','edit-table'):'<p>학급 시간표는 선생님이 관리합니다.</p>')}<button class="button primary">설정 저장하고 시작하기</button></form><p>${e(cloud.user.email)} · ${cloud.user.role==='admin'?'관리자':'회원'} ${c.person?.teacher_status==='approved'?'· 승인된 선생님':''}</p>${btn('로그아웃','logout')}${btn('내 자료 백업','backup')}${btn('이전 로그인 전 기록 가져오기','import-local')}</section>${appearancePanel(p)}${remindersPanel(p,{focus:false})}<section class="panel"><h2>학교·학급 연결</h2><p>소통 페이지에서 학급과 그룹에 직접 입장하거나 탈퇴할 수 있어요. 역할 변경은 관리자에게 문의하세요.</p><p>관리자는 개인 채팅·학급·그룹 대화를 열람할 수 있습니다.</p></section>`;}
function render(){
 if(booting){$('#app').innerHTML='<main class="login-shell"><h1>내 계정을 확인하고 있어요…</h1></main>';return;}
 if(!cloud.user){applyAppearance(null);$('#app').innerHTML=authScreen();return;}
 if(adminRoute){view='admin';applyAppearance(s.data.profile.appearance);$('#app').innerHTML='<main class="admin-shell"><header class="campus-header"><span>메타시간표 · 관리자 전용</span>'+btn('로그아웃','logout')+'</header>'+(cloud.user.role==='admin'?adminPage(s.admin,s.adminError):'<section class="panel"><h1>접근 권한이 없습니다.</h1><p>관리자 계정만 사용할 수 있습니다.</p><a href="/">메타시간표로 돌아가기</a></section>')+'</main>';if(cloud.user.role==='admin'&&!s.admin&&!s.adminLoading&&!s.adminError)loadAdmin();return;}
 if(!s.data.profile.campusOnboarded)view='settings';
 if(!visiblePages().some(([v])=>v===view))view='home';
 applyAppearance(s.data.profile.appearance);const cap=capacity(),p=plan(s.data.tasks,cap,today());
 $('#app').innerHTML=`<aside class="campus-sidebar"><a class="brand" href="#home">${logo} 메타시간표</a><p class="muted">시간을 아끼다, 메타시간표</p><nav aria-label="주 메뉴">${visiblePages().map(([v,[icon,name]])=>`<a href="#${v}" class="campus-nav ${view===v?'active':''}" ${view===v?'aria-current="page"':''}><span>${icon}</span>${name}${v==='social'?' <small id="unread-count"></small>':''}</a>`).join('')}</nav><button class="profile-shortcut" data-action="profile"><span class="avatar">${e(s.data.profile.name.slice(0,1)||'나')}</span><span><b>${e(s.data.profile.name)}</b><small>프로필 · 개인 설정</small></span></button></aside><main id="main" class="campus-main" tabindex="-1"><header class="campus-header"><span id="current-clock">${new Date().toLocaleString('ko-KR')}</span><span id="save-status" role="status">${e(cloud.status)}</span></header>${cloud.locked?'<p class="warning-text">저장이 잠겼어요. 설정의 백업으로 임시 기록을 보관한 뒤 새로고침해 주세요.</p>':''}${s.community.site?.announcement?'<section class="panel site-announcement">'+e(s.community.site.announcement)+'</section>':''}${view==='admin'?adminPage(s.admin,s.adminError):view==='home'?homePage(s,p,dailyCapacity(cap,today())):view==='entry'?entryPage(s):view==='planner'?plannerPage(s,weekPlan(s.data.tasks,cap,today(),s.planWeek)):view==='tutor'?tutorPage(s):view==='social'?socialPage(s):settings()}</main>`;
 if(view==='admin'&&!s.admin&&!s.adminLoading&&!s.adminError)loadAdmin();
 updateUnread();restore();const setup=$('#profile-form');if(setup?.querySelector('.schedule-editor')&&s.schoolKey===['school','grade','className'].map(k=>setup.elements[k].value.trim()).join('|')){const timing=setup.querySelector('.schedule-editor details');if(timing)timing.hidden=!!s.school?.schedule;setup.querySelectorAll('[name^=slot-]').forEach(el=>el.readOnly=!!s.school?.table);setup.querySelectorAll('[data-action=analyze-schedule],[data-action=science-preset],#schedule-photo').forEach(el=>el.disabled=!!s.school?.schedule);}for(const d of document.querySelectorAll('details'))d.open=openedDetails.has(view+':'+d.querySelector('summary')?.textContent);if(view==='home'){loadTable(s.homeWeek);loadTable(sunday(today()));}if(view==='entry')loadTable(s.entryWeek);
}
async function loadAdmin(page=0,q='',section=s.admin?.section||'users'){if(cloud.user?.role!=='admin')return;s.adminLoading=true;s.adminError=false;try{s.admin={...await api('/api/admin?section='+section+'&page='+page+'&q='+encodeURIComponent(q)),q};}catch(err){s.adminError=true;error(err);}finally{s.adminLoading=false;if(view==='admin')render();}}
async function openSchedule(id){const r=await api('/api/schedule?id='+encodeURIComponent(id));if(r.status!=='complete')throw new Error('완료된 분석 결과가 아니에요.');if(!$('#table-form'))$('#campus-dialog')?.close();if(!$('#table-form')&&!$('#profile-form .schedule-editor')){$('#campus-dialog')?.close();await editTable();}const f=$('#table-form')||$('#profile-form');fillSchedule(f,r.result);const box=f.querySelector('#schedule-photo-preview');box.innerHTML='<p>사진 분석 초안이에요. 아래 과목·시각을 확인한 뒤 저장하세요.</p>'+r.result.uncertainties.map(x=>'<p class="warning-text">'+e(x)+'</p>').join('')+'<a href="#settings/'+e(id)+'">이 분석 결과 다시 열기</a>';capture();}
function modal(title,body){$('#campus-dialog')?.remove();const d=document.createElement('dialog');d.id='campus-dialog';d.innerHTML=`<div class="panel-heading"><h2>${e(title)}</h2>${btn('닫기','close-dialog')}</div>${body}`;document.body.append(d);d.showModal();d.addEventListener('close',()=>d.remove());}
function editTask(id){const t=s.data.tasks.find(t=>t.id===id);if(!t)return;s.entries=[{...structuredClone(t),taskType:typeOf(t),totalMinutes:t.totalMinutes??t.minutes,warnings:[]}];s.entryIndex=0;s.entryText=t.source||t.title;s.editId=id;go('entry');}
function pasteNotice(text,base=today()){capture();const rows=inspectNotice(text,s.data.tasks,base,subjectList());s.entries=rows.map(r=>({...r.parsed,taskType:r.old?typeOf(r.old):typeOf(r.parsed),priority:r.parsed.priority!==2?r.parsed.priority:r.old?.priority||2,difficulty:r.parsed.difficulty||r.old?.difficulty||2,durationRequired:!r.old,note:r.old?.note||'',completedMinutes:r.old?.completedMinutes||0,totalMinutes:r.parsed.minutesEstimated?(r.old?.totalMinutes??r.parsed.totalMinutes):r.parsed.totalMinutes,fields:{...r.parsed.fields,...r.old?.fields,...Object.fromEntries(Object.entries(r.parsed.fields).filter(([,v])=>v!==null))},noticeRow:r,targetId:r.targetId,warnings:r.warnings}));s.entryIndex=0;s.editId=null;s.entryText=text;$('#campus-dialog')?.close();go('entry');}
async function editTable(){schedulePhoto=null;const week=s.homeWeek,shared=await getSchool(s.data.profile,week);modal('시간표·일과 편집 · '+dayLabel(week),`<form id="table-form">${scheduleEditor(s.data.profile,week,{...s.classTables[week],...shared?.table,...shared?.schedule})}<button class="button primary">시간표 저장</button></form>`);const f=$('#table-form');if(shared?.schedule&&!shared.schedule.canEdit){f.querySelector('.schedule-editor details').hidden=true;f.querySelectorAll('[data-action=analyze-schedule],[data-action=science-preset],#schedule-photo').forEach(el=>el.disabled=true);f.insertAdjacentHTML('afterbegin','<p>학교 공통 일과는 최초 등록자 또는 승인된 선생님이 관리해요.</p>');}if(shared?.table&&!shared.table.canEdit){f.querySelectorAll('[name^=slot-]').forEach(el=>el.readOnly=true);f.insertAdjacentHTML('afterbegin','<p>이 반의 과목 시간표는 최초 등록자 또는 승인된 선생님이 관리해요.</p>');}}
function planDay(date){const cap=capacity(),p=weekPlan(s.data.tasks,cap,today(),sunday(date)),d=p.days.find(d=>d.date===date);modal(dayLabel(date)+' 자세한 계획',`${d.items.map(i=>`<article class="compact-task"><strong>${e(s.data.tasks.find(t=>t.id===i.id)?.fields.subject||'')} · ${e(i.title)} · ${i.minutes}분</strong>${btn('할일 수정','edit',`data-id="${e(i.id)}"`)}</article>`).join('')||'<p>배치된 할일이 없어요.</p>'}<h3>이 날짜에 직접 배치</h3><form id="pin-form"><input type="hidden" name="date" value="${date}"><label>할일<select name="taskId">${s.data.tasks.filter(t=>!t.done&&['study','assignment'].includes(t.category)).map(t=>`<option value="${e(t.id)}">${e(t.title)}</option>`).join('')}</select></label><label>배치할 시간 (0이면 이 날짜 직접 배치 해제)<input type="number" name="minutes" min="0" max="720" required value="30"></label><button class="button primary">배치 저장</button></form><h3>이날 일일 시간 조정</h3><form id="capacity-form"><input type="hidden" name="date" value="${date}"><label>총 일일 시간 (분)<input name="minutes" type="number" min="0" max="720" required value="${s.data.profile.dateOverrides?.[date]??s.data.profile.weeklyMinutes[new Date(date+'T12:00:00').getDay()]}"></label><button class="button secondary">시간 변경</button></form><details><summary>직접 배치 전체 확인</summary>${s.data.tasks.flatMap(t=>(t.planSlots||[]).map(slot=>`<p>${e(t.title)} · ${slot.date} · ${slot.minutes}분 ${btn('해제','unpin',`data-id="${e(t.id)}" data-date="${slot.date}"`)}</p>`)).join('')}</details>`);}
async function room(id){const result=await api('/api/campus?room='+id);s.room=result.room;s.messages=result.messages;go('social');if(result.messages.length)await campus('read-room',{roomId:id,through:result.messages.at(-1).created_at});await refreshCommunity();updateUnread();}
async function openAnswer(id){const r=await api('/api/tutor?id='+encodeURIComponent(id));if(r.status!=='complete')throw new Error('완료되지 않은 답변이에요.');Object.assign(s.tutor,{...r,revealed:1,image:null});view='tutor';location.hash='tutor/'+id;render();}
const route=()=>location.hash.slice(1).split('/')[0];
async function loadMeals(){
 const id=cloud.user?.id;if(!id)return;
 try{const r=await api('/api/meals');if(cloud.user?.id!==id)return;s.meals=r.text;if(view==='home'){capture();render();}}
 catch{if(cloud.user?.id===id)s.meals='급식 정보를 불러오지 못했어요.';}
}
function updateUnread(){const n=(s.community.rooms||[]).reduce((sum,r)=>sum+(r.unread||0),0);document.title=(n?'('+n+') ':'')+'시간을 아끼다, 메타시간표';const el=$('#unread-count');if(el)el.textContent=n?'새 메시지 '+n+'개':'';}
async function start(){
 try{
  const result=await loadCloud();
  if(result){
   s.data=upgrade(result.data);s.userId=cloud.user.id;
   try{const d=JSON.parse(sessionStorage.getItem('campus-draft-'+cloud.user.id)||'null');if(d)Object.assign(s,d);}catch{}
   if(adminRoute)return;
   await refreshCommunity();
   if(s.data.profile.campusOnboarded)loadTable(sunday(today()));
   const ai=await api('/api/tutor').catch(()=>({enabled:false,history:[]}));
   Object.assign(s.tutor,{enabled:ai.enabled,history:ai.history,remaining:ai.remaining});
  }
 }catch(err){error(err);}
 finally{
  booting=false;view=pages[route()]?route():'home';render();
  const id=location.hash.split('/')[1];if(view==='tutor'&&id&&cloud.user)openAnswer(id).catch(error);if(view==='settings'&&id&&cloud.user)openSchedule(id).catch(error);
 }
}
cloud.onStatus=text=>{if($('#save-status'))$('#save-status').textContent=text;if(/실패|충돌|만료/.test(text))feedback(text+' · 입력 내용을 백업하고 연결 상태를 확인해 주세요.','error');else if(text==='클라우드 저장 중…')feedback('저장 중입니다. 잠시만 기다려 주세요.','pending');else if(text==='클라우드 저장됨'&&!booting)feedback('변경 내용을 저장했습니다.','success');};
window.addEventListener('hashchange',()=>{capture();view=pages[route()]?route():'home';const id=location.hash.split('/')[1];if(view==='tutor'&&id&&s.tutor.id!==id&&cloud.user)openAnswer(id).catch(error);render();if(view==='settings'&&id&&cloud.user)openSchedule(id).catch(error);window.scrollTo(0,0);});
document.addEventListener('input',event=>{if(event.target.id==='peer-query'){const q=event.target.value.trim().toLowerCase(),peers=s.community.people.filter(p=>p.name.toLowerCase().includes(q)||p.user_id.toLowerCase().includes(q));const box=$('#peer-results');if(box)box.innerHTML=q?peers.map(p=>'<article class="compact-task"><span>'+e(p.name)+' · '+e(p.grade)+'학년 '+e(p.class_name)+'반<small>ID '+e(p.user_id)+'</small></span>'+btn('1:1 채팅','direct-chat','data-id="'+e(p.user_id)+'"')+'</article>').join('')||'<p>검색 결과가 없어요. 같은 학교·학급 연결과 상대방의 공개 동의를 확인해 주세요.</p>':'';return;}if(event.target.closest('#profile-form')&&['school','grade','className'].includes(event.target.name)){clearTimeout(schoolTimer);schoolTimer=setTimeout(checkSchool,500);}if(event.target.id==='entry-text'){s.entryText=event.target.value;clearTimeout(saveTimer);saveTimer=setTimeout(()=>{try{const previous=s.entries;if(!s.editId){s.entries=s.entryText.trim()?parseBatch(s.entryText,today(),subjectList()).map((raw,i)=>{const p=resolveEntry(raw);return {...p,taskType:p.taskType||typeOf(p),startDate:null,deadlinePeriod:p.deadlinePeriod||null,...(previous[i]&&!previous[i].durationRequired?{totalMinutes:previous[i].totalMinutes,durationRequired:false}: {})};}):[];s.entryIndex=0;}else if(s.entryText.trim()){const old=previous[0];s.entries[0]={...old,...entryParse(s.entryText,today()),totalMinutes:old.totalMinutes,durationRequired:false,completedMinutes:old.completedMinutes,note:old.note};}persist();if($('#entry-options'))renderEntry();}catch(err){error(err);}},350);}else if(event.target.closest('#entry-form')){captureEntry();if(event.target.name==='time'){const d=s.entries[s.entryIndex];if(d)d.deadlineAuto=false;}persist();}else if(event.target.closest('#tutor-form')){const v=fd($('#tutor-form'));s.tutor.subject=v.subject;s.tutor.mode=v.mode;s.tutor.question=v.question;}else capture();if(event.target.closest('#appearance-form')){const v=fd($('#appearance-form'));applyAppearance({mode:v.mode,accent:v.accent,secondary:v.secondary,background:v.customBackground?v.background:null});}});
function renderEntry(){const focus=$('#entry-text'),start=focus?.selectionStart,end=focus?.selectionEnd,focused=document.activeElement===focus;render();if(focused&&$('#entry-text')){$('#entry-text').focus();$('#entry-text').setSelectionRange(start,end);}}
document.addEventListener('change',async event=>{if(event.target.id==='schedule-photo'){const file=event.target.files[0];if(!file)return;schedulePhoto=null;if(file.size>2097152||!['image/png','image/jpeg','image/webp'].includes(file.type))return toast('PNG/JPG/WebP 2MB 이하를 선택하세요.');const reader=new FileReader();reader.onload=()=>{schedulePhoto=reader.result;$('#schedule-photo-preview').innerHTML='<img class="problem-photo" alt="확인할 시간표 사진" src="'+e(schedulePhoto)+'">';};reader.readAsDataURL(file);return;}if(event.target.id==='problem-photo'){const file=event.target.files[0];if(!file)return;if(file.size>2*1024*1024||!['image/png','image/jpeg','image/webp'].includes(file.type))return toast('PNG/JPG/WebP, 2MB 이하 사진을 선택하세요.');const reader=new FileReader();reader.onload=()=>{s.tutor.image=reader.result;render();};reader.readAsDataURL(file);}else if(event.target.closest('#entry-form')){captureEntry();const d=s.entries[s.entryIndex];if(d&&['subject','due'].includes(event.target.name)){Object.assign(d,resolveEntry(d));renderEntry();}if(d&&event.target.name==='time')d.deadlineAuto=false;persist();}else if(event.target.closest('#tutor-form')&&['subject','mode'].includes(event.target.name)){const v=fd($('#tutor-form'));s.tutor={...s.tutor,subject:v.subject,mode:v.mode,question:v.question,result:null};render();}else capture();});
document.addEventListener('click',async event=>{const b=event.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action,key='click:'+a+':'+(b.dataset.id||b.dataset.room||''),label=b.innerHTML;if(inflight.has(key))return toast('처리 중입니다. 잠시만 기다려 주세요.');inflight.add(key);b.disabled=true;b.setAttribute('aria-busy','true');const busyTimer=setTimeout(()=>{if(b.isConnected)b.textContent='처리 중… 잠시만 기다려 주세요';},250);try{
 if(a==='close-dialog')return $('#campus-dialog')?.close();if(!cloud.user)return;
 if(a==='meals'){const offset=Number(b.dataset.offset)||0;modal(offset?'내일 급식':'오늘 급식','<p class="meal-text">급식을 불러오고 있어요.</p>');try{const r=await api('/api/meals?offset='+offset),el=$('#campus-dialog .meal-text');if(el)el.textContent=r.text;}catch(err){const el=$('#campus-dialog .meal-text');if(el)el.textContent=err.message;}return;}if(a==='profile')return go('settings');if(a==='logout'){capture();await disablePush();await signOut();s.data=null;s.userId=null;s.school=null;s.schoolKey=null;s.pendingFingerprint=null;schoolRequest++;clearTimeout(saveTimer);clearTimeout(schoolTimer);s.forms={};s.entries=[];s.entryText='';s.editId=null;s.entryIndex=0;s.meals='급식 연결을 확인하고 있어요.';s.tutor={enabled:false,subject:'수학',mode:'concept',question:'',image:null,result:null,revealed:1,history:[]};s.room=null;s.messages=[];s.community={member:null,person:null,people:[],notices:[],rooms:[],applications:[]};s.admin=null;s.adminError=false;schedulePhoto=null;s.classTables={};render();return;}
 if(role()==='teacher'&&['complete','edit','delete-task','receive-task','unpin','paste-notice','reflect','import-local','plan-day'].includes(a))throw new Error('선생님은 학급 운영 기능을 이용해 주세요.');
 if(a==='edit'){capture();$('#campus-dialog')?.close();return editTask(b.dataset.id);}if(a==='cancel-edit'){s.entries=[];s.entryText='';s.editId=null;render();return;}
 if(a==='delete-task'){
  const id=b.dataset.id,t=s.data.tasks.find(t=>t.id===id);if(!t)return;
  if(cloud.locked)throw new Error('저장이 잠겼어요. 새로고침 후 다시 시도해 주세요.');
  if(!confirm('“'+t.title+'” 할일을 삭제할까요?\n메모·진행 기록·직접 배치도 삭제되며 되돌릴 수 없어요. 이미 공유한 채팅 메시지는 유지됩니다.'))return;
  s.data={...s.data,tasks:removeTask(s.data.tasks,id)};save();clearTimeout(saveTimer);
  if(s.editId===id||s.entries.some(d=>d.targetId===id)){s.entries=[];s.entryIndex=0;s.entryText='';s.editId=null;}
  if(s.forms['message-form']?.taskId===id)delete s.forms['message-form'].taskId;
  persist();$('#campus-dialog')?.close();if(view==='entry')go('planner');else render();
  await saved();feedback('할일을 삭제하고 저장했습니다.','success');return;
 }
 if(role()==='teacher'&&['complete','edit','receive-task','unpin'].includes(a))throw new Error('선생님은 학급 운영 기능을 이용해 주세요.');
 if(a==='entry-tab'){captureEntry();s.entryIndex=Number(b.dataset.index);render();return;}
 if(a==='complete'){const t=s.data.tasks.find(t=>t.id===b.dataset.id);if(t){if(!t.done&&remainingMinutes(t)>0)Object.assign(t,recordStudy(t,remainingMinutes(t),crypto.randomUUID(),new Date().toISOString()));t.done=!t.done;save();render();}return;}
 if(a==='month'){captureEntry();const key=b.dataset.key+'Month';s[key]=moveMonth(s[key],Number(b.dataset.step));render();return;}
 if(a==='table-week'){captureEntry();const key=b.dataset.key+'Week';s[key]=addDays(s[key],Number(b.dataset.step)*7);render();return;}
 if(a==='plan-week'){const next=addDays(s.planWeek,Number(b.dataset.step)*7);if(next>addDays(today(),730))return toast('주간 계획은 앞으로 2년까지 확인할 수 있어요.');s.planWeek=next;render();return;}if(a==='plan-today'){s.planWeek=sunday(today());render();return;}
 if(a==='date'||a==='period'){const date=b.dataset.date,period=a==='period'?Number(b.dataset.period):null;if(b.dataset.key==='entry'){if(a==='date'&&event.detail>0)return;captureEntry();if(!s.entries.length){s.entries=[entryParse(s.entryText||'새 할일',today())];s.entryIndex=0;}const d=s.entries[s.entryIndex];d.fields.due=date;d.startDate=null;d.deadlinePeriod=period;d.fields.time=period?(s.classTables[s.entryWeek]?.periodTimes||s.data.profile.periodTimes||PERIODS)[period-1]:null;d.deadlineAuto=false;if(period){const table=tableFor(s.data.profile,s.classTables[s.entryWeek],s.entryWeek),day=new Date(date+'T12:00:00').getDay();d.fields.subject=table[day-1]?.[period-1]?.replace(/\([^)]*\)/g,'').trim()||d.fields.subject;d.lessonNote=date+' '+period+'교시 시작('+d.fields.time+')까지';}else Object.assign(d,resolveEntry(d));persist();render();}else{s.homeSelection={date,period,time:period?(s.classTables[s.homeWeek]?.periodTimes||s.data.profile.periodTimes||PERIODS)[period-1]:null};const box=$('#selected-home-tasks');if(box)box.innerHTML=selectedHomeTasks(s);}return;}
 if(a==='condition'){s.data.profile.conditions=Object.fromEntries(Object.entries({...s.data.profile.conditions,[today()]:b.dataset.value}).sort(([a],[z])=>a.localeCompare(z)).slice(-366));save();render();toast('컨디션을 반영했어요. 마감 우선순위와 직접 배치는 유지해요.');return;}
 if(a==='plan-day')return planDay(b.dataset.date);if(a==='unpin'){const t=s.data.tasks.find(t=>t.id===b.dataset.id);t.planSlots=t.planSlots.filter(p=>p.date!==b.dataset.date);save();$('#campus-dialog')?.close();render();return;}
 if(a==='paste-notice'){modal('공지 붙여넣기',`<form id="paste-form"><label>카톡·다른 매체의 공지<textarea name="text" maxlength="12000" required></textarea></label><button class="button primary">분석하고 추가 화면으로</button></form>`);return;}
 if(a==='reflect'){const n=s.community.notices.find(n=>n.id===b.dataset.id);return pasteNotice(n.body,new Date(new Date(n.created_at).getTime()+9*3600000).toISOString().slice(0,10));}if(a==='write-notice'){if(!canPublish(role()))return modal('권한 안내','<p>선생님과 임원의 권한입니다</p>');if(!s.community.member)return modal('학급 연결 필요','<p>소통에서 학급에 먼저 입장하세요.</p>');modal('우리 반 공지 쓰기','<form id="notice-form"><label>제목<input name="title" maxlength="200" required></label><label>공지 내용<textarea name="text" maxlength="12000" required></textarea></label><button class="button primary">학급에 게시하기</button></form>');return;}
 if(a==='edit-table')return editTable();
 if(a==='direct-chat'){const r=await campus('room',{name:'개인 대화',members:[b.dataset.id]});await refreshCommunity();return await room(r.id);}if(a==='open-room')return await room(b.dataset.id);if(a==='refresh-room')return await room(s.room.id);
 if(a==='receive-task'){const t=s.messages.find(m=>m.id===b.dataset.id)?.shared;if(t){s.entries=[{...parseEntry(t.title,today()),...t,fields:{...parseEntry(t.title,today()).fields,...t.fields},taskType:t.taskType||typeOf(t),source:t.title,sourceDate:today(),warnings:[],minutesEstimated:false,durationRequired:false}];s.entryIndex=0;s.entryText=t.title;s.editId=null;go('entry');}return;}
 if(a==='open-answer')return await openAnswer(b.dataset.id);if(a==='remove-photo'){s.tutor.image=null;render();return;}if(a==='reveal-step'){s.tutor.revealed=Math.min(3,s.tutor.revealed+1);render();return;}
 if(a==='palette'){const f=$('#appearance-form');f.elements.accent.value=PALETTES[b.dataset.palette][1];capture();const v=fd(f);applyAppearance({mode:v.mode,accent:v.accent,secondary:v.secondary,background:v.customBackground?v.background:null});return;}
 if(a==='enable-push'){await enablePush();toast('이 기기의 새 채팅·공지 알림을 등록했어요.');return;}if(a==='disable-push'){await disablePush();toast('이 기기의 소통 알림을 껐어요.');return;}
 if(a==='enable-reminders'){await enableReminders();localStorage.setItem('meta-reminders-'+cloud.user.id,'enabled');toast('브라우저 알림을 켰어요.');return;}if(a==='disable-reminders'){localStorage.removeItem('meta-reminders-'+cloud.user.id);toast('브라우저 알림을 껐어요.');return;}
 if(a==='calendar-export'||a==='backup'){const content=a==='backup'?JSON.stringify(cloud.locked?JSON.parse(sessionStorage.getItem('radar-pending-'+cloud.user.id)||'null')?.data||s.data:s.data,null,2):calendarFile(s.data.tasks),url=URL.createObjectURL(new Blob([content],{type:a==='backup'?'application/json':'text/calendar'})),link=document.createElement('a');link.href=url;link.download=a==='backup'?'meta-timetable-backup.json':'meta-timetable.ics';link.click();setTimeout(()=>URL.revokeObjectURL(url),2000);return;}
 if(a==='import-local'){const old=JSON.parse(localStorage.getItem('byeonsaeng-radar-v1')||'null');if(!old?.tasks?.length)return toast('이전 로그인 전 기록이 없어요.');if(!validateBackup(old))throw new Error('이전 기록 형식이 올바르지 않아요.');if(!confirm('이 브라우저의 이전 할일을 내 계정으로 복사할까요?'))return;const ids=new Set(s.data.tasks.map(t=>t.id));const next={...s.data,tasks:[...s.data.tasks,...upgrade(old).tasks.filter(t=>!ids.has(t.id))]};if(!validateBackup(next))throw new Error('가져오면 저장 한도를 초과해요.');s.data=next;save();render();return;}
 if(a==='create-class'){await campus(a);await refreshCommunity();render();toast('학급을 개설했어요. 같은 소속 학생은 코드 없이 입장할 수 있어요.');return;}
 if(a==='join-class'){if(!confirm('같은 소속의 학급에 참여합니다. 관리자와 담당 선생님이 소속을 확인하며 관리자는 모든 대화를 열람할 수 있어요. 입장할까요?'))return;await campus('join',{classId:b.dataset.id,consent:true});await refreshCommunity();s.classTables={};render();return;}
 if(a==='kick-class'){if(!confirm('학생을 추방하고 재입장을 제한할까요?'))return;await campus(a,{userId:b.dataset.id});await refreshCommunity();render();return;}
 if(a==='create-group'){modal('그룹 개설 신청','<form id="group-create-form"><label>그룹 이름<input name="name" maxlength="100" required></label><label>입장 방식<select name="visibility"><option value="public">코드 없이 공개 입장</option><option value="code">코드 입장</option></select></label><label>직접 정하는 코드 (코드 입장일 때)<input name="code" type="password" minlength="8" maxlength="64" autocomplete="new-password"></label><label class="checkbox-label"><input name="schoolOnly" type="checkbox">우리 학교 회원만 입장</label><label class="checkbox-label"><input name="consent" type="checkbox" required>관리자 승인 후 개설되며 모든 대화를 관리자가 열람할 수 있음을 확인했습니다.</label><button class="button primary">개설 신청</button></form>');return;}
 if(a==='join-group'){modal('그룹 입장','<form id="group-join-form" data-id="'+e(b.dataset.id)+'">'+(b.dataset.visibility==='code'?'<label>그룹 코드<input name="code" type="password" maxlength="64" required></label>':'<p>코드 없이 입장할 수 있어요.</p>')+'<label class="checkbox-label"><input name="consent" type="checkbox" required>관리자가 모든 대화를 열람할 수 있음을 확인하고 참여합니다.</label><button class="button primary">입장하기</button></form>');return;}
 if(a==='share-task'){const classRoom=s.community.rooms.find(r=>r.kind==='class'),groups=s.community.rooms.filter(r=>r.kind==='group');modal('할일 공유하기','<p>개인 메모와 진행 기록은 공유하지 않습니다.</p>'+btn('우리 반에 공유','share-destination','data-task="'+e(b.dataset.id)+'" data-room="'+e(classRoom?.id||'')+'" data-kind="class"')+groups.map(r=>btn(e(r.name)+'에 공유','share-destination','data-task="'+e(b.dataset.id)+'" data-room="'+r.id+'" data-kind="group"')).join('')+(!groups.length?'<p>그룹에 입장하면 학생도 그룹에 공유할 수 있어요.</p>':''));return;}
 if(a==='share-destination'){if(b.dataset.kind==='class'&&!canPublish(role()))return modal('권한 안내','<p>선생님과 임원의 권한입니다</p>');if(!b.dataset.room)return toast('소통에서 학급에 먼저 입장하세요.');await saved();await campus('message',{roomId:b.dataset.room,taskId:b.dataset.task,clientId:crypto.randomUUID()});$('#campus-dialog').close();toast('할일을 공유했어요.');return;}
 if(a==='admin-section'){s.admin=null;return await loadAdmin(0,'',b.dataset.section);}
 if(a==='admin-room'){const d=await api('/api/admin?room='+b.dataset.id+(b.dataset.before?'&before='+encodeURIComponent(b.dataset.before):''));modal(d.room.name,adminMessages(d));return;}
 if(a==='admin-table'){const c=s.admin.affiliations[Number(b.dataset.index)],d=await api('/api/admin?table=1&school='+encodeURIComponent(c.school)+'&grade='+encodeURIComponent(c.grade)+'&className='+encodeURIComponent(c.class_name));modal(c.school+' '+c.grade+'학년 '+c.class_name+'반',adminTable(d));return;}
 if(a==='admin-mutate'){if(!confirm('이 관리 작업을 적용할까요? 폐쇄·추방은 참여자의 접근을 즉시 차단합니다.'))return;await api('/api/admin',{method:'POST',body:JSON.stringify({action:b.dataset.op,id:b.dataset.id,userId:b.dataset.user})});$('#campus-dialog')?.close();return await loadAdmin(s.admin.page,s.admin.q);}
 if(a==='admin-edit-group'){const r=s.admin.rooms.find(r=>r.id===b.dataset.id);modal('그룹 편집','<form id="admin-group-form" data-id="'+r.id+'"><label>그룹 이름<input name="name" value="'+e(r.name)+'" required maxlength="100"></label><label>입장 방식<select name="visibility"><option value="public">공개</option><option value="code" '+(r.visibility==='code'?'selected':'')+'>코드</option></select></label><label>새 코드 (기존 코드 유지 시 비움)<input name="code" type="password" minlength="8" maxlength="64"></label><label>입장 가능한 학교 (모든 학교는 비움)<input name="school" value="'+e(r.school||'')+'" maxlength="100"></label><button class="button primary">저장</button></form>');return;}
 if(a==='admin-edit-class'){const c=s.admin.classes.find(c=>c.id===b.dataset.id);modal('학급 편집','<p>회원과 담당자의 소속이 모두 일치해야 합니다.</p><form id="admin-class-form" data-id="'+c.id+'">'+[['school','학교',c.school],['grade','학년',c.grade],['className','반',c.class_name],['ownerId','담당 선생님 사용자 ID',c.owner_id]].map(([k,l,v])=>'<label>'+l+'<input name="'+k+'" value="'+e(v)+'" required maxlength="100"></label>').join('')+'<button class="button primary">저장</button></form>');return;}
 if(a==='admin-retry')return await loadAdmin();
 if(a==='admin-page')return await loadAdmin(Number(b.dataset.page),s.admin.q);
 if(a==='admin-suspend'){if(!confirm(b.dataset.suspend==='true'?'이 회원의 이용을 정지할까요?':'이 회원의 이용을 복구할까요?'))return;await api('/api/admin',{method:'POST',body:JSON.stringify({action:'suspend',userId:b.dataset.id,suspended:b.dataset.suspend==='true'})});return await loadAdmin(s.admin.page,s.admin.q);}
 if(a==='admin-report'){if(!confirm('신고를 처리 완료로 기록할까요?'))return;await api('/api/admin',{method:'POST',body:JSON.stringify({action:'resolve-report',reportId:b.dataset.id})});return await loadAdmin(s.admin.page,s.admin.q);}
 if(a==='schedule-history'){const r=await api('/api/schedule');modal('내 시간표 분석 기록',r.history.map(g=>'<p><a href="#settings/'+e(g.id)+'">'+new Date(g.created_at).toLocaleString('ko-KR')+' · '+e(g.status)+'</a></p>').join('')||'<p>아직 기록이 없어요.</p>');return;}
 if(a==='analyze-schedule'){if(!schedulePhoto)throw new Error('사진을 먼저 선택하세요.');const f=b.closest('form');b.disabled=true;try{toast('사진을 읽고 있어요. 저장 전 결과를 확인해 주세요.');const r=await api('/api/schedule',{method:'POST',body:JSON.stringify({image:schedulePhoto,consent:!!f.elements.scheduleConsent.checked})});await openSchedule(r.id);toast('입력란에 분석 초안을 채웠어요. 확인 후 저장해 주세요.');}finally{b.disabled=false;}return;}
 if(a==='science-preset'){if(!confirm('사진으로 제공된 대전과학고 시간표 예시로 입력란을 바꿀까요? 저장 전 수정할 수 있어요.'))return;fillSchedule(b.closest('form'),sciencePreset());capture();return;}
 if(a==='add-schedule-row'){const f=b.closest('form'),rows=f.querySelectorAll('.schedule-row');if(rows.length>=30)return toast('일과는 최대 30개입니다.');const index=rows.length,html=scheduleRows([{label:'',start:'19:00',end:'20:00',period:null,days:[1,2,3,4,5],examOnly:false}]).replaceAll('-0"','-'+index+'"');f.querySelector('.schedule-rows').insertAdjacentHTML('beforeend',html);return;}
 if(a==='approve-teacher'){if(!confirm(b.dataset.approve==='true'?'실제 선생님임을 확인했나요? 승인하면 학급 운영 권한을 얻습니다.':'이 요청을 반려할까요?'))return;await campus(a,{userId:b.dataset.id,approve:b.dataset.approve==='true'});}
 if(a==='leader')await campus(a,{userId:b.dataset.id,role:b.dataset.role||'student'});
 if(a==='block'){if(!confirm('이 사용자를 차단할까요?'))return;await campus(a,{userId:b.dataset.id});}
 if(a==='leave-class'){if(!confirm(s.community.member?.owner_id===s.userId?'담당 선생님이 탈퇴하면 학급이 폐쇄되고 학생도 퇴장합니다. 탈퇴할까요?':'학급에서 탈퇴할까요? 다른 그룹·개인 할일은 유지됩니다.'))return;await campus(a);s.room=null;s.messages=[];s.classTables={};}
 if(a==='leave-room'){if(!confirm('대화방을 나가면 더 이상 메시지를 볼 수 없어요. 나갈까요?'))return;await campus(a,{roomId:s.room.id});s.room=null;s.messages=[];}
 if(a==='report-room'){const reason=prompt('신고 사유를 적어 주세요.');if(!reason)return;await campus('report',{roomId:s.room.id,reason});return;}
 await refreshCommunity();render();
 }catch(err){error(err);}finally{clearTimeout(busyTimer);inflight.delete(key);if(b.isConnected){b.disabled=false;b.removeAttribute('aria-busy');b.innerHTML=label;}}});
document.addEventListener('pointerdown',event=>{const b=event.target.closest('[data-action=date][data-key=entry]');if(b&&!b.disabled){captureEntry();drag={start:b.dataset.date,end:b.dataset.date};}});
document.addEventListener('pointerover',event=>{const b=event.target.closest('[data-action=date][data-key=entry]');if(drag&&b&&!b.disabled){drag.end=b.dataset.date;const[a,z]=normalizedRange(drag.start,drag.end);document.querySelectorAll('[data-action=date][data-key=entry]').forEach(x=>x.classList.toggle('in-range',x.dataset.date>=a&&x.dataset.date<=z));}});
document.addEventListener('pointerup',()=>{if(!drag)return;if(!s.entries.length){s.entries=[entryParse(s.entryText||'새 할일',today())];s.entryIndex=0;}const[a,z]=normalizedRange(drag.start,drag.end),d=s.entries[s.entryIndex];d.startDate=a===z?null:a;d.fields.due=z;d.fields.time=null;d.deadlinePeriod=null;d.deadlineAuto=false;Object.assign(d,resolveEntry(d));drag=null;persist();render();});
document.addEventListener('submit',async event=>{const f=event.target;if(!f.id)return;event.preventDefault();const key='form:'+f.id;if(inflight.has(key))return formFeedback(f,'처리 중입니다. 잠시만 기다려 주세요.','pending');inflight.add(key);const button=event.submitter||f.querySelector('button[type=submit],button:not([type])'),label=button?.innerHTML;const v=fd(f);if(button){button.disabled=true;button.textContent='처리 중… 잠시만 기다려 주세요';button.setAttribute('aria-busy','true');}formFeedback(f,'처리 중입니다. 잠시만 기다려 주세요.','pending');dismissFeedback();let failed=false;try{
 if(f.id==='group-create-form'){await campus('create-group',{...v,schoolOnly:!!v.schoolOnly,consent:!!v.consent});$('#campus-dialog').close();await refreshCommunity();render();toast('관리자에게 개설 승인을 요청했어요. 승인 후 직접 입장하세요.');return;}
 if(f.id==='group-join-form'){const r=await campus('join-group',{roomId:f.dataset.id,code:v.code,consent:!!v.consent});$('#campus-dialog').close();await refreshCommunity();return await room(r.id);}
 if(['admin-group-form','admin-class-form'].includes(f.id)){await api('/api/admin',{method:'POST',body:JSON.stringify({action:f.id==='admin-group-form'?'edit-group':'edit-class',id:f.dataset.id,...v})});$('#campus-dialog').close();return await loadAdmin(s.admin.page,s.admin.q);}
 if(f.classList.contains('admin-role-form')){if(!confirm('실제 신원과 소속을 확인했나요? 담당 선생님을 다른 역할로 바꾸면 그 학급은 폐쇄됩니다. 역할을 변경할까요?'))return;await api('/api/admin',{method:'POST',body:JSON.stringify({action:'role',userId:f.dataset.user,role:v.role})});return await loadAdmin(s.admin.page,s.admin.q);}
 if(['login-form','signup-form','reset-code-form','reset-password-form'].includes(f.id)){await authAction(f.id.replace('-form',''),v);if(f.id.startsWith('reset')){formFeedback(f,f.id==='reset-password-form'?'비밀번호를 변경했습니다. 새 비밀번호로 로그인하세요.':'인증 메일을 요청했습니다. 받은편지함과 스팸함을 확인해 주세요.','success');return;}s.forms={};s.entries=[];booting=true;render();await start();return;}
 if(!cloud.user)throw new Error('로그인이 필요해요.');
 if(f.id==='profile-form'){const p={...s.data.profile,name:v.name.trim(),school:v.school.trim(),grade:v.grade.trim(),className:v.className.trim(),weeklyMinutes:[0,1,2,3,4,5,6].map(d=>Number(v['capacity-'+d])),onboarded:true,campusOnboarded:true};if(!validProfile(p))throw new Error('개인 설정을 확인해 주세요.');const m=s.community.member;if(m&&[p.school,p.grade,p.className].join('|')!==[m.school,m.grade,m.class_name].join('|'))throw new Error('학급 연결 중에는 소속을 바꿀 수 없어요. 먼저 학급 연결을 해제하세요.');if(f.querySelector('.schedule-editor')){const rows=scheduleFromFields(v);p.daySchedule=rows;p.examMode=!!v.examMode;p.periodTimes=Array.from({length:9},(_,i)=>rows.find(r=>r.period===i+1)?.start||PERIODS[i]);p.timetable=Array.from({length:5},(_,d)=>Array.from({length:9},(_,i)=>v['slot-'+d+'-'+i]||''));}const shared=await getSchool(p);if(shared?.schedule)Object.assign(p,{daySchedule:shared.schedule.daySchedule,periodTimes:shared.schedule.periodTimes});if(shared?.table)p.timetable=shared.table.table;s.data.profile=p;save();await saved();await sharedSetup();await campus('profile',{discoverable:!!v.discoverable});delete s.forms[f.id];await refreshCommunity();go('home');return;}
 if(f.id==='entry-form'){clearTimeout(saveTimer);captureEntry();for(const d of s.entries){if(d.fields.due)await loadTable(sunday(d.fields.due));Object.assign(d,resolveEntry(d));}if(!s.entries.length)throw new Error('할일을 입력하세요.');if(s.entries.some(d=>(d.warnings?.length||d.noticeRow?.choice==='choose'))&&!confirm('모호한 항목의 제목·분류·날짜·시간을 확인했나요? 확정하지 못한 항목은 새 할일로 추가됩니다.'))return;const next={...s.data,tasks:commitEntries(s.data.tasks,s.entries,s.editId)};if(!validateBackup(next))throw new Error('제목·기간·완료한 시간 등 입력 범위를 확인해 주세요.');s.data=next;save();s.entries=[];s.entryText='';s.editId=null;persist();go('planner');return;}
 if(f.id==='paste-form')return pasteNotice(v.text);
 if(f.id==='notice-form'){await campus('notice',v);$('#campus-dialog').close();await refreshCommunity();render();return;}
 if(f.id==='table-form'){const table=Array.from({length:5},(_,d)=>Array.from({length:9},(_,i)=>v['slot-'+d+'-'+i]||'')),daySchedule=scheduleFromFields(v),periodTimes=Array.from({length:9},(_,i)=>daySchedule.find(r=>r.period===i+1)?.start||s.data.profile.periodTimes?.[i]||PERIODS[i]),examMode=!!v.examMode;const shared=await getSchool(s.data.profile,s.homeWeek);if(!shared?.schedule||shared.schedule.canEdit)await api('/api/school',{method:'POST',body:JSON.stringify({action:'schedule',daySchedule,periodTimes,revision:shared?.schedule?.revision})});if(!shared?.table||shared.table.canEdit)await api('/api/school',{method:'POST',body:JSON.stringify({action:'table',week:s.homeWeek,table,revision:shared?.table?.week?.slice(0,10)===s.homeWeek?shared.table.revision:undefined})});if(s.community.member){await campus('timetable',{week:s.homeWeek,table,periodTimes,daySchedule,examMode});s.classTables[s.homeWeek]={table,periodTimes,daySchedule,examMode};}else{s.data.profile.timetableWeeks={...s.data.profile.timetableWeeks,[s.homeWeek]:table};Object.assign(s.data.profile,{periodTimes,daySchedule,examMode});save();}$('#campus-dialog').close();render();return;}
 if(f.id==='pin-form'){const t=s.data.tasks.find(t=>t.id===v.taskId),n=Number(v.minutes);if(!t||!validDate(v.date)||v.date<today()||v.date>finishBy(t)||t.startDate&&v.date<t.startDate||!Number.isInteger(n)||n<0||n>remainingMinutes(t))throw new Error('기간·마감 전날·남은 시간을 확인하세요.');t.planSlots=[...(t.planSlots||[]).filter(p=>p.date!==v.date),...(n?[{date:v.date,minutes:n}]:[])];save();$('#campus-dialog').close();render();return;}
 if(f.id==='capacity-form'){const n=Number(v.minutes);if(!Number.isInteger(n)||n<0||n>720||v.date<today())throw new Error('일일 시간은 0~720분입니다.');s.data.profile.dateOverrides={...s.data.profile.dateOverrides,[v.date]:n};save();$('#campus-dialog').close();render();return;}
 if(f.id==='appearance-form'){const p={mode:v.mode,accent:v.accent,secondary:v.secondary,background:v.customBackground?v.background:null};if(!validAppearance(p))throw new Error('테마를 확인하세요.');s.data.profile.appearance=p;save();}
 if(f.id==='reminder-settings-form'){const p={times:[0,1,2].map(i=>v['time-'+i]).filter(Boolean).sort(),weekdays:[0,1,2,3,4,5,6].filter(d=>v['day-'+d]),deadline:!!v.deadline,focus:!!v.focus};if(!validReminders(p))throw new Error('알림 시각은 중복 없이, 요일은 한 개 이상 골라 주세요.');s.data.profile.reminderSettings=p;save();}
 if(f.id==='admin-search')return await loadAdmin(0,v.q);
 if(f.id==='admin-site-form'){await api('/api/admin',{method:'POST',body:JSON.stringify({action:'site',sharing_enabled:!!v.sharing_enabled,notices_enabled:!!v.notices_enabled,announcement:v.announcement})});await refreshCommunity();return await loadAdmin(s.admin.page,s.admin.q);}
 if(f.id==='shared-task-form'){await campus('message',{roomId:s.room.id,text:v.text||'',sharedDraft:{title:v.title,subject:v.subject,due:v.due,minutes:Number(v.minutes)}});delete s.forms[f.id];return await room(s.room.id);}
 if(f.id==='teacher-request-form')await campus('request-teacher',v);
 if(f.id==='join-form'){await campus('join',{code:v.code,consent:!!v.consent});s.classTables={};}
 if(f.id==='room-form'){const ids=new FormData(f).getAll('peer');const r=await campus('room',{name:v.name,members:ids});await refreshCommunity();delete s.forms[f.id];return await room(r.id);}
 if(f.id==='message-form'){if(v.taskId&&s.room.kind!=='group'&&!canPublish(role()))return modal('권한 안내','<p>선생님과 임원의 권한입니다</p>');await saved();const previous=s.forms[f.id],fingerprint=JSON.stringify([s.room.id,v.text,v.taskId||null]);const clientId=previous?.fingerprint===fingerprint&&previous.clientId||crypto.randomUUID();s.pendingFingerprint=fingerprint;s.forms[f.id]={...v,clientId,fingerprint};persist();await campus('message',{roomId:s.room.id,text:v.text,taskId:v.taskId||null,clientId});delete s.forms[f.id];return await room(s.room.id);}
 if(f.id==='tutor-form'){s.tutor.result=null;toast('AI가 질문을 확인하고 있어요. 최대 45초 정도 걸릴 수 있어요.');const r=await api('/api/tutor',{method:'POST',body:JSON.stringify({subject:v.subject,mode:v.mode,question:v.question,image:s.tutor.image,consent:!!v.consent})});const status=await api('/api/tutor');Object.assign(s.tutor,{history:status.history,remaining:status.remaining});delete s.forms[f.id];await openAnswer(r.id);toast('답변을 내 계정에 저장했어요.');return;}
 if(f.id==='teacher-question-form'){if(!v.teacher)throw new Error('질문할 선생님을 선택하세요.');const r=await campus('room',{name:s.tutor.subject+' 질문',members:[v.teacher]});await campus('message',{roomId:r.id,text:v.question});await refreshCommunity();return await room(r.id);}
 delete s.forms[f.id];await refreshCommunity();render();toast('저장했어요.');
 }catch(err){failed=true;formFeedback(f,err.message||'처리에 실패했습니다. 다시 시도해 주세요.','error');error(err);}finally{inflight.delete(key);if(button){button.disabled=false;button.removeAttribute('aria-busy');button.innerHTML=label;}if(!failed&&f.isConnected&&f.querySelector('.form-feedback')?.dataset.kind==='pending'){f.querySelector('.form-feedback')?.remove();}}});
setInterval(async()=>{if(adminRoute||booting||!cloud.user)return;const clock=$('#current-clock');const lesson=$('#current-lesson');if(lesson){const config=scheduleFor(s.data.profile,s.classTables[sunday(today())]),now=currentLesson(config.rows,tableFor(s.data.profile,s.classTables[sunday(today())],sunday(today())),new Date(),config.examMode);lesson.textContent=now?'지금 · '+now.label+' · '+now.subject+' ('+now.start+'~'+now.end+')':'지금 · 등록된 수업·일과 시간이 아니에요';}if(clock)clock.textContent=new Date().toLocaleString('ko-KR');const m=today()+':'+new Date().getMinutes();if(m!==minute&&!document.querySelector('dialog[open]')&&!document.querySelector('form:focus-within')&&['home','planner'].includes(view)){minute=m;capture();render();}},1000);
setInterval(async()=>{if(booting||!cloud.user)return;try{if(typeof Notification==='undefined'||Notification.permission!=='granted'||localStorage.getItem('meta-reminders-'+cloud.user.id)!=='enabled')return;const p=s.data.profile.reminderSettings||defaultReminders(),key='meta-reminders-'+cloud.user.id+'-sent',sent=JSON.parse(localStorage.getItem(key)||'{}'),now=Date.now();if(s.data.tasks.some(t=>!t.done))for(const time of scheduledReminderSlots(p)){const tag='daily:'+today()+':'+time;if(!sent[tag]){await showReminder('설정한 시각이에요. 오늘의 할일을 확인하세요.');sent[tag]=now;}}if(p.deadline)for(const t of s.data.tasks.filter(t=>!t.done&&t.fields.due)){const due=deadlineStamp(t),tag=t.id+':'+due;if(due>=now&&due-now<=1800000&&!sent[tag]){await showReminder('곧 마감인 할일이 있어요.');sent[tag]=now;}}for(const[k,v]of Object.entries(sent))if(now-v>172800000)delete sent[k];localStorage.setItem(key,JSON.stringify(sent));}catch{}},15000);
document.addEventListener('invalid',event=>{const input=event.target;formFeedback(input.form,input.validationMessage||'필수 항목과 입력 형식을 확인해 주세요.','error');},true);
window.addEventListener('online',()=>{retrySave();});start();render();
setInterval(async()=>{if(booting||!cloud.user||document.hidden||!['home','social'].includes(view)||document.querySelector('dialog[open],form:focus-within'))return;const id=cloud.user.id;await refreshCommunity();if(cloud.user?.id!==id)return;capture();s.classTables={};render();},60000);

async function pollMessages(){if(adminRoute||polling||booting||!cloud.user||document.hidden)return;polling=true;try{const id=cloud.user.id,previous=new Map((s.community.rooms||[]).map(r=>[r.id,r.latest]));await refreshCommunity();if(cloud.user?.id!==id)return;updateUnread();for(const r of s.community.rooms||[])if(r.unread&&r.latest&&previous.get(r.id)!==r.latest&&!(view==='social'&&s.room?.id===r.id))toast('새 메시지가 있어요. 소통에서 확인하세요.');if(view==='social'&&s.room){const roomId=s.room.id,result=await api('/api/campus?room='+roomId);if(cloud.user?.id!==id)return;if(s.room?.id===roomId){s.messages=result.messages;if($('#messages'))$('#messages').innerHTML=messagesHtml(s);if(result.messages.length){await campus('read-room',{roomId,through:result.messages.at(-1).created_at});const r=s.community.rooms.find(r=>r.id===roomId);if(r)r.unread=0;updateUnread();}}}if(view==='social'&&!document.querySelector('dialog[open],form:focus-within')){capture();render();}}catch(err){if([401,403].includes(err.status)){s.room=null;s.messages=[];delete s.forms['message-form'];if(view==='social')render();}error(err);}finally{polling=false;}}
setInterval(pollMessages,10000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)pollMessages();});window.addEventListener('online',pollMessages);
