import {cloud,loadCloud,queueSave,retrySave,authAction,signOut,api} from './cloud.js';
import {authPage} from './account-ui.js';
import {upgrade,validProfile} from './profile.js';
import {plan,today,iso,addDays,validateBackup,validDate} from './engine.js';
import {parseEntry,TYPES,PERIODS,sunday,moveMonth,normalizedRange,weekPlan,emptyTable,tableFor,typeOf} from './campus-model.js';
import {createQuickTask} from './quick-entry.js';
import {commitEntries,removeTask} from './campus-entry.js';
import {inspectNotice,applyNoticeRows} from './notice-intake.js';
import {remainingMinutes,dailyCapacity,recordStudy} from './workload.js';
import {finishBy,deadlineStamp} from './live-time.js';
import {applyAppearance,PALETTES,validAppearance,validReminders,defaultReminders,scheduledReminderSlots} from './preferences.js';
import {appearancePanel} from './preferences-ui.js';
import {remindersPanel,enableReminders,showReminder,calendarFile} from './reminders.js';
import {e,btn,dayLabel,entryOptions,entryPage,homePage,plannerPage,socialPage,tutorPage,messagesHtml,taskLine} from './campus-ui.js';
const $=q=>document.querySelector(q),pages={home:['⌂','메인'],entry:['＋','할일 추가'],planner:['▦','주간 계획'],tutor:['✧','공부 도우미'],social:['☏','소통'],settings:['⚙','설정']};
const s={data:null,userId:null,community:{member:null,person:null,people:[],notices:[],rooms:[],applications:[]},classTables:{},homeWeek:sunday(today()),entryWeek:sunday(today()),planWeek:sunday(today()),homeMonth:today(),entryMonth:today(),entries:[],entryIndex:0,entryText:'',editId:null,forms:{},room:null,messages:[],tutor:{enabled:false,subject:'수학',mode:'concept',question:'',image:null,result:null,revealed:1},meals:'급식 연결을 확인하고 있어요.'};
let booting=true,view='home',drag=null,minute='',noticeTimer,saveTimer;
const openedDetails=new Set();
document.addEventListener('toggle',event=>{const d=event.target;if(d.tagName!=='DETAILS'||!d.isConnected)return;const key=view+':'+d.querySelector('summary')?.textContent;d.open?openedDetails.add(key):openedDetails.delete(key);},true);
const toast=text=>{$('#toast').textContent=text;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('#toast').textContent='',6000);};
const error=err=>toast(err.message||'요청을 처리하지 못했어요.');
const fd=f=>Object.fromEntries(new FormData(f));
function persist(){if(!cloud.user)return;try{sessionStorage.setItem('campus-draft-'+cloud.user.id,JSON.stringify({forms:s.forms,entries:s.entries,entryIndex:s.entryIndex,entryText:s.entryText,editId:s.editId}));}catch{toast('초안 임시 저장이 어려워요. 입력 내용을 복사해 주세요.');}}
function capture(){if(!cloud.user)return;for(const f of document.querySelectorAll('form')){if(['tutor-form','entry-form'].includes(f.id))continue;if(f.querySelector('[type=password]'))continue;s.forms[f.id]=fd(f);for(const c of f.querySelectorAll('[type=checkbox]'))s.forms[f.id][c.name]=c.checked;}captureEntry();persist();}
function restore(){for(const[id,values]of Object.entries(s.forms)){const f=document.getElementById(id);if(!f)continue;for(const[k,v]of Object.entries(values)){const el=f.elements.namedItem(k);if(!el||!el.tagName||el.type==='file')continue;if(el.type==='checkbox')el.checked=!!v;else el.value=v;}}}
function captureEntry(){const f=$('#entry-form'),d=s.entries[s.entryIndex];if(!f||!d||!f.elements.title)return;const v=fd(f);Object.assign(d,{title:v.title,taskType:v.taskType,category:['study','bring','buy','other'].includes(v.taskType)?v.taskType:'assignment',totalMinutes:Number(v.minutes),priority:Number(v.priority),difficulty:Number(v.difficulty),note:v.note||'',completedMinutes:Number(v.completedMinutes||0),startDate:v.startDate||null});Object.assign(d.fields,{subject:v.subject||null,due:v.due||null,time:v.time||null});}
function capacity(){const now=Date.now(),spent=s.data.tasks.reduce((sum,t)=>sum+(t.studyLog||[]).filter(l=>iso(new Date(l.at))===today()).reduce((n,l)=>n+l.minutes,0),0);return {weekly:s.data.profile.weeklyMinutes,overrides:s.data.profile.dateOverrides||{},today:today(),now,spent};}
function save(){if(!cloud.user)throw new Error('로그인이 필요해요.');if(cloud.locked)throw new Error('저장이 잠겼어요. 백업 후 새로고침해 주세요.');if(!validateBackup(s.data))throw new Error('날짜·시간·입력 범위를 확인해 주세요.');s.data.acceptedPlan=null;queueSave(s.data);}
async function saved(){const end=Date.now()+20000;while(cloud.running||cloud.pending){if(cloud.locked||Date.now()>end)throw new Error('개인 설정 저장이 완료된 뒤 다시 시도해 주세요.');await new Promise(r=>setTimeout(r,200));}}
async function campus(action,body={}){return api('/api/campus',{method:'POST',body:JSON.stringify({action,...body})});}
async function refreshCommunity(){const id=cloud.user?.id;if(!id)return;try{const c=await api('/api/campus');if(cloud.user?.id===id){s.community=c;if(s.room?.auto_kind&&!c.rooms.some(r=>r.id===s.room.id)){s.room=null;s.messages=[];delete s.forms['message-form'];}}}catch(err){toast('학급 연결: '+err.message);}}
async function loadTable(week){if(!cloud.user||!s.community.member||Object.hasOwn(s.classTables,week))return;const id=cloud.user.id;try{const r=await api('/api/campus?week='+week);if(cloud.user?.id===id){s.classTables[week]=r.table;if(['home','entry'].includes(view)){capture();render();}}}catch(err){error(err);}}
function go(next){if(!pages[next])next='home';view=next;if(location.hash!=='#'+next)location.hash=next;render();window.scrollTo(0,0);}
function authScreen(){return `<main class="login-shell"><a class="login-brand" href="#home">▦ 메타시간표</a><h1>내 시간에서, 우리 반까지.</h1><p>로그인하면 나만의 계획과 학교 소식을 한곳에서 볼 수 있어요.</p>${authPage(null).replace(/<button class="text-button" data-action="demo">.*?<\/button>/,'').replace('학교 정보는 선택 입력입니다.','처음 로그인하면 학교·학년·반과 일일 시간을 입력합니다.').replace('로그인 전 사용하던 기록은 자동 업로드하지 않습니다. 로그인 후 직접 가져올 수 있어요.','이전 버전의 로그인 전 기록은 설정에서 직접 가져올 수 있어요.')}</main>`;}
function settings(){const p=s.data.profile,c=s.community;return `<section class="panel"><h1>${p.campusOnboarded?'나의 설정':'처음 한 번, 나에게 맞게'}</h1><p>한 줄 입력 → 옵션 확인 → 추가하기. 선생님이 없어도 개인 모드로 쓸 수 있어요.</p><form id="profile-form"><div class="form-grid">${[['name','표시 이름'],['school','학교 이름 (정확히)'],['grade','학년'],['className','반']].map(([k,l])=>`<label>${l}<input name="${k}" maxlength="100" required value="${e(p[k])}"></label>`).join('')}</div><p class="muted">학교 이름이 같아도 자동 연결되지 않아요. 선생님의 학급 초대 코드가 필요해요.</p><h2>요일별 일일 시간</h2><div class="week-inputs">${[0,1,2,3,4,5,6].map(d=>`<label>${'일월화수목금토'[d]}<input name="capacity-${d}" type="number" min="0" max="720" required value="${p.weeklyMinutes[d]}"><small>분</small></label>`).join('')}</div><label class="checkbox-label"><input name="discoverable" type="checkbox" ${c.person?.discoverable?'checked':''}>학급 연결 후 같은 학교 사용자에게 표시 이름·학년·반을 공개하고, 같은 학교·같은 반 자동 그룹에 참여하며 채팅 초대를 받겠습니다.</label><button class="button primary">설정 저장하고 시작하기</button></form><p>${e(cloud.user.email)} · ${cloud.user.role==='admin'?'관리자':'회원'} ${c.person?.teacher_status==='approved'?'· 승인된 선생님':''}</p>${btn('로그아웃','logout')}${btn('내 자료 백업','backup')}${btn('이전 로그인 전 기록 가져오기','import-local')}</section>${appearancePanel(p)}${remindersPanel(p,{focus:false})}<section class="panel"><h2>학교 연결·선생님 계정</h2><p>현재 ${c.member?e(c.member.school)+' '+e(c.member.grade)+'학년 '+e(c.member.class_name)+'반':'개인 모드'}</p>${c.member?.role==='teacher'?btn('새 학급 초대 코드 발급','invite'):!c.member&&(c.person?.teacher_status==='approved'||cloud.user.role==='admin')?btn('내 소속으로 학급 만들기','create-class'):''}<form id="teacher-request-form"><label>담당 과목 / 승인 요청 사유<input name="subjects" maxlength="200" required value="${e(c.person?.subjects)}"></label><button class="button secondary" ${c.person?.teacher_status==='pending'?'disabled':''}>${c.person?.teacher_status==='pending'?'선생님 승인 대기 중':'선생님 역할 신청'}</button></form>${cloud.user.role==='admin'?`<h2>선생님 승인 요청</h2>${c.applications.map(a=>`<article class="compact-task"><span>${e(a.name)} · ${e(a.school)} · ${e(a.subjects)}</span>${btn('신원 확인 후 승인','approve-teacher',`data-id="${e(a.user_id)}" data-approve="true"`)}${btn('반려','approve-teacher',`data-id="${e(a.user_id)}" data-approve="false"`)}</article>`).join('')||'<p>요청이 없습니다.</p>'}<h2>접수된 신고</h2>${(c.reports||[]).map(r=>`<p>${e(r.reason)} · ${new Date(r.created_at).toLocaleDateString('ko-KR')}</p>`).join('')||'<p>신고가 없습니다.</p>'}<p class="muted">이메일 인증이 없으므로 실제 선생님 여부를 별도 연락으로 확인한 뒤 승인하세요.</p>`:''}</section>`;}
function render(){
 if(booting){$('#app').innerHTML='<main class="login-shell"><h1>내 계정을 확인하고 있어요…</h1></main>';return;}
 if(!cloud.user){applyAppearance(null);$('#app').innerHTML=authScreen();return;}
 if(!s.data.profile.campusOnboarded)view='settings';
 applyAppearance(s.data.profile.appearance);const cap=capacity(),p=plan(s.data.tasks,cap,today());
 $('#app').innerHTML=`<aside class="campus-sidebar"><a class="brand" href="#home">▦ 메타시간표</a><p class="muted">내 시간에서, 우리 반까지</p><nav aria-label="주 메뉴">${Object.entries(pages).map(([v,[icon,name]])=>`<a href="#${v}" class="campus-nav ${view===v?'active':''}" ${view===v?'aria-current="page"':''}><span>${icon}</span>${name}</a>`).join('')}</nav><button class="profile-shortcut" data-action="profile"><span class="avatar">${e(s.data.profile.name.slice(0,1)||'나')}</span><span><b>${e(s.data.profile.name)}</b><small>프로필 · 개인 설정</small></span></button></aside><main id="main" class="campus-main" tabindex="-1"><header class="campus-header"><span id="current-clock">${new Date().toLocaleString('ko-KR')}</span><span id="save-status" role="status">${e(cloud.status)}</span></header>${cloud.locked?'<p class="warning-text">저장이 잠겼어요. 설정의 백업으로 임시 기록을 보관한 뒤 새로고침해 주세요.</p>':''}${view==='home'?homePage(s,p,dailyCapacity(cap,today())):view==='entry'?entryPage(s):view==='planner'?plannerPage(s,weekPlan(s.data.tasks,cap,today(),s.planWeek)):view==='tutor'?tutorPage(s):view==='social'?socialPage(s):settings()}</main>`;
 restore();for(const d of document.querySelectorAll('details'))d.open=openedDetails.has(view+':'+d.querySelector('summary')?.textContent);if(view==='home')loadTable(s.homeWeek);if(view==='entry')loadTable(s.entryWeek);
}
function modal(title,body){$('#campus-dialog')?.remove();const d=document.createElement('dialog');d.id='campus-dialog';d.innerHTML=`<div class="panel-heading"><h2>${e(title)}</h2>${btn('닫기','close-dialog')}</div>${body}`;document.body.append(d);d.showModal();d.addEventListener('close',()=>d.remove());}
function editTask(id){const t=s.data.tasks.find(t=>t.id===id);if(!t)return;s.entries=[{...structuredClone(t),taskType:typeOf(t),totalMinutes:t.totalMinutes??t.minutes,warnings:[]}];s.entryIndex=0;s.entryText=t.source||t.title;s.editId=id;go('entry');}
function pasteNotice(text,base=today()){capture();const rows=inspectNotice(text,s.data.tasks,base);s.entries=rows.map(r=>({...r.parsed,taskType:r.old?typeOf(r.old):typeOf(r.parsed),priority:r.old?.priority||2,difficulty:r.old?.difficulty||3,note:r.old?.note||'',completedMinutes:r.old?.completedMinutes||0,totalMinutes:r.parsed.minutesEstimated?(r.old?.totalMinutes??r.parsed.totalMinutes):r.parsed.totalMinutes,fields:{...r.parsed.fields,...r.old?.fields,...Object.fromEntries(Object.entries(r.parsed.fields).filter(([,v])=>v!==null))},noticeRow:r,targetId:r.targetId,warnings:r.warnings}));s.entryIndex=0;s.editId=null;s.entryText=text;$('#campus-dialog')?.close();go('entry');}
function editTable(){const week=s.homeWeek,t=tableFor(s.data.profile,s.classTables[week],week),times=s.classTables[week]?.periodTimes||s.data.profile.periodTimes||PERIODS;modal('시간표 편집 · '+dayLabel(week),`<p>선생님이 연결된 학급은 선생님만 편집해요. 이 주부터 적용합니다.</p><form id="table-form"><div class="table-scroll"><table class="school-table"><thead><tr><th>교시 시작</th>${[...'월화수목금'].map(d=>'<th>'+d+'</th>').join('')}</tr></thead><tbody>${Array.from({length:9},(_,i)=>`<tr><th><input name="time-${i}" type="time" required value="${times[i]}"></th>${[0,1,2,3,4].map(d=>`<td><input name="slot-${d}-${i}" maxlength="100" value="${e(t[d][i])}" aria-label="${'월화수목금'[d]} ${i+1}교시"></td>`).join('')}</tr>`).join('')}</tbody></table></div><button class="button primary">시간표 저장</button></form>`);}
function planDay(date){const cap=capacity(),p=weekPlan(s.data.tasks,cap,today(),sunday(date)),d=p.days.find(d=>d.date===date);modal(dayLabel(date)+' 자세한 계획',`${d.items.map(i=>`<article class="compact-task"><strong>${e(i.title)} · ${i.minutes}분</strong>${btn('할일 수정','edit',`data-id="${e(i.id)}"`)}</article>`).join('')||'<p>배치된 할일이 없어요.</p>'}<h3>이 날짜에 직접 배치</h3><form id="pin-form"><input type="hidden" name="date" value="${date}"><label>할일<select name="taskId">${s.data.tasks.filter(t=>!t.done&&['study','assignment'].includes(t.category)).map(t=>`<option value="${e(t.id)}">${e(t.title)}</option>`).join('')}</select></label><label>배치할 시간 (0이면 이 날짜 직접 배치 해제)<input type="number" name="minutes" min="0" max="720" required value="30"></label><button class="button primary">배치 저장</button></form><h3>이날 일일 시간 조정</h3><form id="capacity-form"><input type="hidden" name="date" value="${date}"><label>총 일일 시간 (분)<input name="minutes" type="number" min="0" max="720" required value="${s.data.profile.dateOverrides?.[date]??s.data.profile.weeklyMinutes[new Date(date+'T12:00:00').getDay()]}"></label><button class="button secondary">시간 변경</button></form><details><summary>직접 배치 전체 확인</summary>${s.data.tasks.flatMap(t=>(t.planSlots||[]).map(slot=>`<p>${e(t.title)} · ${slot.date} · ${slot.minutes}분 ${btn('해제','unpin',`data-id="${e(t.id)}" data-date="${slot.date}"`)}</p>`)).join('')}</details>`);}
async function room(id){const result=await api('/api/campus?room='+id);s.room=result.room;s.messages=result.messages;go('social');}
async function openAnswer(id){const r=await api('/api/tutor?id='+encodeURIComponent(id));if(r.status!=='complete')throw new Error('완료되지 않은 답변이에요.');Object.assign(s.tutor,{...r,revealed:1,image:null});view='tutor';location.hash='tutor/'+id;render();}
const route=()=>location.hash.slice(1).split('/')[0];
async function loadMeals(){
 const id=cloud.user?.id;if(!id)return;
 try{const r=await api('/api/meals');if(cloud.user?.id!==id)return;s.meals=r.text;if(view==='home'){capture();render();}}
 catch{if(cloud.user?.id===id)s.meals='급식 정보를 불러오지 못했어요.';}
}
async function start(){
 try{
  const result=await loadCloud();
  if(result){
   s.data=upgrade(result.data);s.userId=cloud.user.id;
   try{const d=JSON.parse(sessionStorage.getItem('campus-draft-'+cloud.user.id)||'null');if(d)Object.assign(s,d);}catch{}
   await refreshCommunity();
   const ai=await api('/api/tutor').catch(()=>({enabled:false,history:[]}));
   Object.assign(s.tutor,{enabled:ai.enabled,history:ai.history,remaining:ai.remaining});loadMeals();
  }
 }catch(err){error(err);}
 finally{
  booting=false;view=pages[route()]?route():'home';render();
  const id=location.hash.split('/')[1];if(view==='tutor'&&id&&cloud.user)openAnswer(id).catch(error);
 }
}
cloud.onStatus=text=>{if($('#save-status'))$('#save-status').textContent=text;};
window.addEventListener('hashchange',()=>{capture();view=pages[route()]?route():'home';const id=location.hash.split('/')[1];if(view==='tutor'&&id&&s.tutor.id!==id&&cloud.user)openAnswer(id).catch(error);render();window.scrollTo(0,0);});
document.addEventListener('input',event=>{if(event.target.id==='entry-text'){s.entryText=event.target.value;clearTimeout(saveTimer);saveTimer=setTimeout(()=>{if(!s.editId){s.entries=s.entryText.trim()?[parseEntry(s.entryText,today())]:[];s.entryIndex=0;}else if(s.entryText.trim())s.entries[0]={...s.entries[0],...parseEntry(s.entryText,today())};persist();const el=$('#entry-options');if(el){renderEntry();}},350);}else if(event.target.closest('#entry-form')){captureEntry();persist();}else if(event.target.closest('#tutor-form')){const v=fd($('#tutor-form'));s.tutor.subject=v.subject;s.tutor.mode=v.mode;s.tutor.question=v.question;}else capture();if(event.target.closest('#appearance-form')){const v=fd($('#appearance-form'));applyAppearance({mode:v.mode,accent:v.accent,background:v.customBackground?v.background:null});}});
function renderEntry(){const focus=$('#entry-text'),start=focus?.selectionStart,end=focus?.selectionEnd,focused=document.activeElement===focus;render();if(focused&&$('#entry-text')){$('#entry-text').focus();$('#entry-text').setSelectionRange(start,end);}}
document.addEventListener('change',async event=>{if(event.target.id==='problem-photo'){const file=event.target.files[0];if(!file)return;if(file.size>2*1024*1024||!['image/png','image/jpeg','image/webp'].includes(file.type))return toast('PNG/JPG/WebP, 2MB 이하 사진을 선택하세요.');const reader=new FileReader();reader.onload=()=>{s.tutor.image=reader.result;render();};reader.readAsDataURL(file);}else if(event.target.closest('#entry-form')){captureEntry();persist();}else if(event.target.closest('#tutor-form')&&['subject','mode'].includes(event.target.name)){const v=fd($('#tutor-form'));s.tutor={...s.tutor,subject:v.subject,mode:v.mode,question:v.question,result:null};render();}else capture();});
document.addEventListener('click',async event=>{const b=event.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action;try{
 if(a==='close-dialog')return $('#campus-dialog')?.close();if(!cloud.user)return;
 if(a==='profile')return go('settings');if(a==='logout'){capture();await signOut();s.data=null;s.userId=null;s.forms={};s.entries=[];s.entryText='';s.editId=null;s.entryIndex=0;s.meals='급식 연결을 확인하고 있어요.';s.tutor={enabled:false,subject:'수학',mode:'concept',question:'',image:null,result:null,revealed:1,history:[]};s.room=null;s.messages=[];s.community={member:null,person:null,people:[],notices:[],rooms:[],applications:[]};s.classTables={};render();return;}
 if(a==='edit'){capture();$('#campus-dialog')?.close();return editTask(b.dataset.id);}if(a==='cancel-edit'){s.entries=[];s.entryText='';s.editId=null;render();return;}
 if(a==='delete-task'){
  const id=b.dataset.id,t=s.data.tasks.find(t=>t.id===id);if(!t)return;
  if(cloud.locked)throw new Error('저장이 잠겼어요. 새로고침 후 다시 시도해 주세요.');
  if(!confirm('“'+t.title+'” 할일을 삭제할까요?\n메모·진행 기록·직접 배치도 삭제되며 되돌릴 수 없어요. 이미 공유한 채팅 메시지는 유지됩니다.'))return;
  s.data={...s.data,tasks:removeTask(s.data.tasks,id)};save();clearTimeout(saveTimer);
  if(s.editId===id||s.entries.some(d=>d.targetId===id)){s.entries=[];s.entryIndex=0;s.entryText='';s.editId=null;}
  if(s.forms['message-form']?.taskId===id)delete s.forms['message-form'].taskId;
  persist();$('#campus-dialog')?.close();if(view==='entry')go('planner');else render();
  toast('할일을 삭제했어요. 복구할 수 없으며, 저장 상태는 화면 위에서 확인할 수 있어요.');return;
 }
 if(a==='entry-tab'){captureEntry();s.entryIndex=Number(b.dataset.index);render();return;}
 if(a==='complete'){const t=s.data.tasks.find(t=>t.id===b.dataset.id);if(t){if(!t.done&&remainingMinutes(t)>0)Object.assign(t,recordStudy(t,remainingMinutes(t),crypto.randomUUID(),new Date().toISOString()));t.done=!t.done;save();render();}return;}
 if(a==='month'){captureEntry();const key=b.dataset.key+'Month';s[key]=moveMonth(s[key],Number(b.dataset.step));render();return;}
 if(a==='table-week'){captureEntry();const key=b.dataset.key+'Week';s[key]=addDays(s[key],Number(b.dataset.step)*7);render();return;}
 if(a==='plan-week'){const next=addDays(s.planWeek,Number(b.dataset.step)*7);if(next>addDays(today(),730))return toast('주간 계획은 앞으로 2년까지 확인할 수 있어요.');s.planWeek=next;render();return;}if(a==='plan-today'){s.planWeek=sunday(today());render();return;}
 if(a==='date'||a==='period'){const date=b.dataset.date,period=a==='period'?Number(b.dataset.period):null;if(b.dataset.key==='entry'){if(a==='date'&&event.detail>0)return;captureEntry();if(!s.entries.length){s.entries=[parseEntry(s.entryText||'새 할일',today())];s.entryIndex=0;}const d=s.entries[s.entryIndex];d.fields.due=date;d.startDate=null;d.deadlinePeriod=period;d.fields.time=period?(s.classTables[s.entryWeek]?.periodTimes||s.data.profile.periodTimes||PERIODS)[period-1]:null;persist();render();}else modal(dayLabel(date)+(period?' '+period+'교시까지':''),s.data.tasks.filter(t=>!t.done&&t.fields.due===date&&(!period||!t.deadlinePeriod||t.deadlinePeriod<=period)).map(t=>taskLine(t)).join('')||'<p>이때 마감할 일이 없어요.</p>');return;}
 if(a==='plan-day')return planDay(b.dataset.date);if(a==='unpin'){const t=s.data.tasks.find(t=>t.id===b.dataset.id);t.planSlots=t.planSlots.filter(p=>p.date!==b.dataset.date);save();$('#campus-dialog')?.close();render();return;}
 if(a==='paste-notice'){modal('공지 붙여넣기',`<form id="paste-form"><label>카톡·다른 매체의 공지<textarea name="text" maxlength="12000" required></textarea></label><button class="button primary">분석하고 추가 화면으로</button></form>`);return;}
 if(a==='reflect'){const n=s.community.notices.find(n=>n.id===b.dataset.id);return pasteNotice(n.body,new Date(new Date(n.created_at).getTime()+9*3600000).toISOString().slice(0,10));}if(a==='write-notice'){modal('우리 반 공지 쓰기','<form id="notice-form"><label>제목<input name="title" maxlength="200" required></label><label>공지 내용<textarea name="text" maxlength="12000" required></textarea></label><button class="button primary">학급에 게시하기</button></form>');return;}
 if(a==='edit-table')return editTable();
 if(a==='open-room')return await room(b.dataset.id);if(a==='refresh-room')return await room(s.room.id);
 if(a==='receive-task'){const t=s.messages.find(m=>m.id===b.dataset.id)?.shared;if(t){s.entries=[{...parseEntry(t.title,today()),...t,fields:{...parseEntry(t.title,today()).fields,...t.fields},taskType:t.taskType||typeOf(t),source:t.title,sourceDate:today(),warnings:[],minutesEstimated:false}];s.entryIndex=0;s.entryText=t.title;s.editId=null;go('entry');}return;}
 if(a==='open-answer')return await openAnswer(b.dataset.id);if(a==='remove-photo'){s.tutor.image=null;render();return;}if(a==='reveal-step'){s.tutor.revealed=Math.min(3,s.tutor.revealed+1);render();return;}
 if(a==='palette'){const f=$('#appearance-form');f.elements.accent.value=PALETTES[b.dataset.palette][1];capture();const v=fd(f);applyAppearance({mode:v.mode,accent:v.accent,background:v.customBackground?v.background:null});return;}
 if(a==='enable-reminders'){await enableReminders();localStorage.setItem('meta-reminders-'+cloud.user.id,'enabled');toast('브라우저 알림을 켰어요.');return;}if(a==='disable-reminders'){localStorage.removeItem('meta-reminders-'+cloud.user.id);toast('브라우저 알림을 껐어요.');return;}
 if(a==='calendar-export'||a==='backup'){const content=a==='backup'?JSON.stringify(cloud.locked?JSON.parse(sessionStorage.getItem('radar-pending-'+cloud.user.id)||'null')?.data||s.data:s.data,null,2):calendarFile(s.data.tasks),url=URL.createObjectURL(new Blob([content],{type:a==='backup'?'application/json':'text/calendar'})),link=document.createElement('a');link.href=url;link.download=a==='backup'?'meta-timetable-backup.json':'meta-timetable.ics';link.click();setTimeout(()=>URL.revokeObjectURL(url),2000);return;}
 if(a==='import-local'){const old=JSON.parse(localStorage.getItem('byeonsaeng-radar-v1')||'null');if(!old?.tasks?.length)return toast('이전 로그인 전 기록이 없어요.');if(!validateBackup(old))throw new Error('이전 기록 형식이 올바르지 않아요.');if(!confirm('이 브라우저의 이전 할일을 내 계정으로 복사할까요?'))return;const ids=new Set(s.data.tasks.map(t=>t.id));const next={...s.data,tasks:[...s.data.tasks,...upgrade(old).tasks.filter(t=>!ids.has(t.id))]};if(!validateBackup(next))throw new Error('가져오면 저장 한도를 초과해요.');s.data=next;save();render();return;}
 if(['create-class','invite'].includes(a)){const r=await campus(a);await refreshCommunity();render();modal('학급 초대 코드',`<p>같은 학교·학년·반 학생에게만 전달하세요. 코드를 다시 발급하면 기존 코드는 무효가 됩니다.</p><pre>${e(r.code)}</pre>`);return;}
 if(a==='approve-teacher'){if(!confirm(b.dataset.approve==='true'?'실제 선생님임을 확인했나요? 승인하면 학급 운영 권한을 얻습니다.':'이 요청을 반려할까요?'))return;await campus(a,{userId:b.dataset.id,approve:b.dataset.approve==='true'});}
 if(a==='leader')await campus(a,{userId:b.dataset.id,enabled:b.dataset.enabled==='true'});
 if(a==='block'){if(!confirm('이 사용자를 차단할까요?'))return;await campus(a,{userId:b.dataset.id});}
 if(a==='leave-class'){if(!confirm('학급과 모든 대화방 연결이 해제됩니다. 개인 할일은 유지돼요. 해제할까요?'))return;await campus(a);s.room=null;s.messages=[];s.classTables={};}
 if(a==='leave-room'){if(!confirm('대화방을 나가면 더 이상 메시지를 볼 수 없어요. 나갈까요?'))return;await campus(a,{roomId:s.room.id});s.room=null;s.messages=[];}
 if(a==='report-room'){const reason=prompt('신고 사유를 적어 주세요.');if(reason)await campus('report',{roomId:s.room.id,reason});return toast('신고를 접수했어요.');}
 await refreshCommunity();render();
 }catch(err){error(err);}});
document.addEventListener('pointerdown',event=>{const b=event.target.closest('[data-action=date][data-key=entry]');if(b&&!b.disabled){captureEntry();drag={start:b.dataset.date,end:b.dataset.date};}});
document.addEventListener('pointerover',event=>{const b=event.target.closest('[data-action=date][data-key=entry]');if(drag&&b&&!b.disabled){drag.end=b.dataset.date;const[a,z]=normalizedRange(drag.start,drag.end);document.querySelectorAll('[data-action=date][data-key=entry]').forEach(x=>x.classList.toggle('in-range',x.dataset.date>=a&&x.dataset.date<=z));}});
document.addEventListener('pointerup',()=>{if(!drag)return;if(!s.entries.length){s.entries=[parseEntry(s.entryText||'새 할일',today())];s.entryIndex=0;}const[a,z]=normalizedRange(drag.start,drag.end),d=s.entries[s.entryIndex];d.startDate=a===z?null:a;d.fields.due=z;d.fields.time=null;d.deadlinePeriod=null;drag=null;persist();render();});
document.addEventListener('submit',async event=>{const f=event.target;if(!f.id)return;event.preventDefault();const button=f.querySelector('button[type=submit],button:not([type])');if(button)button.disabled=true;try{const v=fd(f);
 if(['login-form','signup-form','reset-code-form','reset-password-form'].includes(f.id)){await authAction(f.id.replace('-form',''),v);if(f.id.startsWith('reset'))return toast('요청을 처리했어요.');s.forms={};s.entries=[];booting=true;render();await start();return;}
 if(!cloud.user)throw new Error('로그인이 필요해요.');
 if(f.id==='profile-form'){const p={...s.data.profile,name:v.name.trim(),school:v.school.trim(),grade:v.grade.trim(),className:v.className.trim(),weeklyMinutes:[0,1,2,3,4,5,6].map(d=>Number(v['capacity-'+d])),onboarded:true,campusOnboarded:true};if(!validProfile(p))throw new Error('개인 설정을 확인해 주세요.');const m=s.community.member;if(m&&[p.school,p.grade,p.className].join('|')!==[m.school,m.grade,m.class_name].join('|'))throw new Error('학급 연결 중에는 소속을 바꿀 수 없어요. 먼저 학급 연결을 해제하세요.');s.data.profile=p;save();await saved();await campus('profile',{discoverable:!!v.discoverable});delete s.forms[f.id];await refreshCommunity();go('home');loadMeals();return;}
 if(f.id==='entry-form'){captureEntry();if(!s.entries.length)throw new Error('할일을 입력하세요.');if(s.entries.some(d=>(d.warnings?.length||d.noticeRow?.choice==='choose'))&&!confirm('모호한 항목의 제목·분류·날짜·시간을 확인했나요? 확정하지 못한 항목은 새 할일로 추가됩니다.'))return;const next={...s.data,tasks:commitEntries(s.data.tasks,s.entries,s.editId)};if(!validateBackup(next))throw new Error('제목·기간·완료한 시간 등 입력 범위를 확인해 주세요.');s.data=next;save();s.entries=[];s.entryText='';s.editId=null;persist();go('planner');return;}
 if(f.id==='paste-form')return pasteNotice(v.text);
 if(f.id==='notice-form'){await campus('notice',v);$('#campus-dialog').close();await refreshCommunity();render();return;}
 if(f.id==='table-form'){const table=Array.from({length:5},(_,d)=>Array.from({length:9},(_,i)=>v['slot-'+d+'-'+i]||'')),periodTimes=Array.from({length:9},(_,i)=>v['time-'+i]);if(s.community.member){await campus('timetable',{week:s.homeWeek,table,periodTimes});s.classTables[s.homeWeek]={table,periodTimes};}else{s.data.profile.timetableWeeks={...s.data.profile.timetableWeeks,[s.homeWeek]:table};s.data.profile.periodTimes=periodTimes;save();}$('#campus-dialog').close();render();return;}
 if(f.id==='pin-form'){const t=s.data.tasks.find(t=>t.id===v.taskId),n=Number(v.minutes);if(!t||!validDate(v.date)||v.date<today()||v.date>finishBy(t)||t.startDate&&v.date<t.startDate||!Number.isInteger(n)||n<0||n>remainingMinutes(t))throw new Error('기간·마감 전날·남은 시간을 확인하세요.');t.planSlots=[...(t.planSlots||[]).filter(p=>p.date!==v.date),...(n?[{date:v.date,minutes:n}]:[])];save();$('#campus-dialog').close();render();return;}
 if(f.id==='capacity-form'){const n=Number(v.minutes);if(!Number.isInteger(n)||n<0||n>720||v.date<today())throw new Error('일일 시간은 0~720분입니다.');s.data.profile.dateOverrides={...s.data.profile.dateOverrides,[v.date]:n};save();$('#campus-dialog').close();render();return;}
 if(f.id==='appearance-form'){const p={mode:v.mode,accent:v.accent,background:v.customBackground?v.background:null};if(!validAppearance(p))throw new Error('테마를 확인하세요.');s.data.profile.appearance=p;save();}
 if(f.id==='reminder-settings-form'){const p={times:[0,1,2].map(i=>v['time-'+i]).filter(Boolean).sort(),weekdays:[0,1,2,3,4,5,6].filter(d=>v['day-'+d]),deadline:!!v.deadline,focus:!!v.focus};if(!validReminders(p))throw new Error('알림 시각은 중복 없이, 요일은 한 개 이상 골라 주세요.');s.data.profile.reminderSettings=p;save();}
 if(f.id==='teacher-request-form')await campus('request-teacher',v);
 if(f.id==='join-form'){await campus('join',{code:v.code,consent:!!v.consent});s.classTables={};}
 if(f.id==='room-form'){const ids=new FormData(f).getAll('peer');const r=await campus('room',{name:v.name,members:ids});await refreshCommunity();delete s.forms[f.id];return await room(r.id);}
 if(f.id==='message-form'){await saved();await campus('message',{roomId:s.room.id,text:v.text,taskId:v.taskId||null});delete s.forms[f.id];return await room(s.room.id);}
 if(f.id==='tutor-form'){s.tutor.result=null;toast('AI가 질문을 확인하고 있어요. 최대 45초 정도 걸릴 수 있어요.');const r=await api('/api/tutor',{method:'POST',body:JSON.stringify({subject:v.subject,mode:v.mode,question:v.question,image:s.tutor.image,consent:!!v.consent})});const status=await api('/api/tutor');Object.assign(s.tutor,{history:status.history,remaining:status.remaining});delete s.forms[f.id];await openAnswer(r.id);toast('답변을 내 계정에 저장했어요.');return;}
 if(f.id==='teacher-question-form'){if(!v.teacher)throw new Error('질문할 선생님을 선택하세요.');const r=await campus('room',{name:s.tutor.subject+' 질문',members:[v.teacher]});await campus('message',{roomId:r.id,text:v.question});await refreshCommunity();return await room(r.id);}
 delete s.forms[f.id];await refreshCommunity();render();toast('저장했어요.');
 }catch(err){error(err);}finally{if(button)button.disabled=false;}});
setInterval(async()=>{if(booting||!cloud.user)return;const clock=$('#current-clock');if(clock)clock.textContent=new Date().toLocaleString('ko-KR');const m=today()+':'+new Date().getMinutes();if(m!==minute&&!document.querySelector('dialog[open]')&&!document.querySelector('form:focus-within')&&['home','planner'].includes(view)){minute=m;capture();render();}},1000);
setInterval(async()=>{if(booting||!cloud.user)return;if(!document.hidden&&view==='social'&&s.room)try{const id=s.room.id,r=await api('/api/campus?room='+id);if(s.room?.id===id){s.messages=r.messages;if($('#messages'))$('#messages').innerHTML=messagesHtml(s);}}catch(err){if([401,403].includes(err.status)){s.room=null;s.messages=[];delete s.forms['message-form'];if(view==='social')render();}};try{if(typeof Notification==='undefined'||Notification.permission!=='granted'||localStorage.getItem('meta-reminders-'+cloud.user.id)!=='enabled')return;const p=s.data.profile.reminderSettings||defaultReminders(),key='meta-reminders-'+cloud.user.id+'-sent',sent=JSON.parse(localStorage.getItem(key)||'{}'),now=Date.now();if(s.data.tasks.some(t=>!t.done))for(const time of scheduledReminderSlots(p)){const tag='daily:'+today()+':'+time;if(!sent[tag]){await showReminder('설정한 시각이에요. 오늘의 할일을 확인하세요.');sent[tag]=now;}}if(p.deadline)for(const t of s.data.tasks.filter(t=>!t.done&&t.fields.due)){const due=deadlineStamp(t),tag=t.id+':'+due;if(due>=now&&due-now<=1800000&&!sent[tag]){await showReminder('곧 마감인 할일이 있어요.');sent[tag]=now;}}for(const[k,v]of Object.entries(sent))if(now-v>172800000)delete sent[k];localStorage.setItem(key,JSON.stringify(sent));}catch{}},15000);
window.addEventListener('online',()=>{retrySave();});start();render();
setInterval(async()=>{if(booting||!cloud.user||document.hidden||!['home','social'].includes(view)||document.querySelector('dialog[open],form:focus-within'))return;const id=cloud.user.id;await refreshCommunity();if(cloud.user?.id!==id)return;capture();s.classTables={};render();},60000);
