import {defaultSchedule,scheduleFor,sciencePreset} from './day-schedule.js';
import {tableFor,PERIODS} from './campus-model.js';
const e=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function scheduleEditor(profile,week,classTable=null){
 const table=tableFor(profile,classTable,week),config=scheduleFor(profile,classTable);
 return `<div class="schedule-editor"><h3>시간표 직접 작성 / 사진으로 입력</h3><button type="button" class="button secondary" data-action="schedule-history">이전 사진 분석 결과</button><p class="muted">학교·반마다 다르게 저장합니다. 사진 분석 결과도 저장 전 확인해 주세요.</p><label>시간표 사진 (선택, 2MB 이하)<input type="file" id="schedule-photo" accept="image/png,image/jpeg,image/webp"></label><div id="schedule-photo-preview"></div><label class="checkbox-label"><input name="scheduleConsent" type="checkbox">사진을 Google Gemini로 전송하는 데 동의합니다. 무료 서비스는 입력을 제품 개선·사람의 검토에 사용할 수 있어요. 개인정보는 가려 주세요.</label><button type="button" class="button secondary" data-action="analyze-schedule">사진에서 시간표 읽기</button><button type="button" class="button secondary" data-action="science-preset">제공된 대전과학고 시간표 예시 불러오기</button><p class="muted">표 전체와 요일·시각이 선명하게 보이는 사진을 올려 주세요. 분석은 약 10~50초 걸리며 성공한 사진은 다시 분석하지 않고 불러옵니다. 예시를 다른 학급에 자동 지정하지 않아요.</p><div class="table-scroll"><table class="school-table"><thead><tr><th>교시</th>${[...'월화수목금'].map(d=>'<th>'+d+'</th>').join('')}</tr></thead><tbody>${Array.from({length:9},(_,i)=>`<tr><th>${i+1}</th>${[0,1,2,3,4].map(d=>`<td><input name="slot-${d}-${i}" maxlength="100" aria-label="${'월화수목금'[d]} ${i+1}교시" value="${e(table[d][i])}"></td>`).join('')}</tr>`).join('')}</tbody></table></div><details><summary>수업 시각·야자·식사 등 일과 편집</summary><p>요일은 일=0, 월=1 … 토=6. 예: 월~금은 1,2,3,4,5. 빈 이름의 줄은 저장하지 않아요.</p><div class="schedule-rows">${scheduleRows(config.rows)}</div><button type="button" class="button secondary" data-action="add-schedule-row">일과 한 줄 추가</button><label class="checkbox-label"><input type="checkbox" name="examMode" ${config.examMode?'checked':''}>시험 기간 일정 표시</label></details></div>`;
}
export function scheduleRows(rows){
 return rows.map((r,i)=>`<div class="schedule-row"><label>이름<input name="schedule-label-${i}" maxlength="60" value="${e(r.label)}"></label><label>시작<input name="schedule-start-${i}" type="time" value="${r.start}"></label><label>종료<input name="schedule-end-${i}" type="time" value="${r.end}"></label><label>교시 (없으면 비움)<input name="schedule-period-${i}" type="number" min="1" max="9" value="${r.period||''}"></label><label>요일<input name="schedule-days-${i}" value="${e(r.days.join(','))}"></label><label class="checkbox-label"><input type="checkbox" name="schedule-exam-${i}" ${r.examOnly?'checked':''}>시험 기간만</label></div>`).join('');
}
export function fillSchedule(form,config){
 for(let d=0;d<5;d++)for(let i=0;i<9;i++)form.elements['slot-'+d+'-'+i].value=config.table[d][i]||'';
 form.querySelector('.schedule-rows').innerHTML=scheduleRows(config.daySchedule||defaultSchedule(config.periodTimes||PERIODS));
 form.elements.examMode.checked=!!config.examMode;
}
