import {nameRooms} from '../server/room-names.js';
import {notifyPeers} from '../server/push.js';
import {randomUUID} from 'node:crypto';
import {db} from '../server/db.js';
import {identity,respond,fail} from '../server/security.js';
import {validTable,validPeriodTimes} from '../src/campus-model.js';
import {validDate} from '../src/engine.js';
import {validDaySchedule} from '../src/day-schedule.js';
import {canPublish} from '../src/roles.js';
import {siteSettings} from '../server/roles.js';
import {roleContext} from '../server/roles.js';
import {roomMember,shareAllowed} from '../server/community-policy.js';
import {communityActions,communityDirectory} from '../server/community-actions.js';
const err=(message,status=400)=>{throw Object.assign(new Error(message),{status});};
const str=(v,max=100)=>{if(typeof v!=='string'||!v.trim()||v.length>max)err('입력 내용을 확인해 주세요.');return v.trim();};
const uuid=v=>typeof v==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(v);
async function limit(sql,user,action,max=30){const minute=Math.floor(Date.now()/60000),[r]=await sql`INSERT INTO public.campus_limits(bucket,hits,expires_at) VALUES (${user+':'+action+':'+minute},1,now()+interval '5 minutes') ON CONFLICT(bucket) DO UPDATE SET hits=campus_limits.hits+1 RETURNING hits`;if(r.hits>max)err('요청이 많아요. 1분 뒤 다시 시도해 주세요.',429);}
export default async function handler(req,res){try{
 if(!['GET','POST'].includes(req.method))return respond(res,405,{error:'Method not allowed'});
 const user=await identity(req),sql=db(),url=new URL(req.url,'https://local.invalid');
 const {person,member,role}=await roleContext(sql,user),site=await siteSettings(sql);
 const roomAccess=async id=>{if(!uuid(id))err('대화방을 확인해 주세요.');const [r]=await sql`SELECT * FROM public.campus_rooms WHERE id=${id}`;if(!r||(!roomMember(r,user.id)||(r.school&&r.school!==person?.school)))err('이 대화방의 참여자가 아닙니다.',403);return r;};
 if(req.method==='GET'){
  if(url.searchParams.has('room')){const room=await roomAccess(url.searchParams.get('room'));const messages=await sql`SELECT m.id,m.sender_id,p.name,m.body,m.shared,m.created_at::text AS created_at FROM public.campus_messages m LEFT JOIN public.campus_people p ON p.user_id=m.sender_id WHERE m.room_id=${room.id} AND NOT EXISTS(SELECT 1 FROM public.campus_blocks b WHERE (b.user_id=${user.id} AND b.blocked_id=m.sender_id) OR (${!!room.auto_key} AND b.blocked_id=${user.id} AND b.user_id=m.sender_id)) ORDER BY m.created_at DESC LIMIT 100`;return respond(res,200,{room:{id:room.id,name:(await nameRooms(sql,[room],user.id))[0].name,members:room.members,kind:room.kind,class_id:room.class_id},messages:messages.reverse()});}
  if(url.searchParams.has('week')){const week=url.searchParams.get('week');if(!validDate(week))err('날짜를 확인하세요.');let table=null;if(member){const [r]=await sql`SELECT payload FROM public.campus_tables WHERE class_id=${member.id} AND week<=${week}::date ORDER BY week DESC LIMIT 1`;table=r?.payload||null;}return respond(res,200,{table});}
  const notices=member?await sql`SELECT n.id,n.title,n.body,n.created_at,p.name AS author FROM public.campus_notices n LEFT JOIN public.campus_people p ON p.user_id=n.author_id WHERE n.class_id=${member.id} ORDER BY n.created_at DESC LIMIT 40`:[];
  const people=person?.discoverable?await sql`SELECT p.user_id,p.name,p.subjects,p.school,p.grade,p.class_name,COALESCE(a.assigned_role,'student') AS role,m.class_id FROM public.campus_people p LEFT JOIN public.campus_accounts a ON a.user_id=p.user_id LEFT JOIN public.campus_members m ON m.user_id=p.user_id WHERE p.school=${person.school} AND p.discoverable=true AND COALESCE(a.suspended,false)=false AND p.user_id<>${user.id} AND NOT EXISTS(SELECT 1 FROM public.campus_blocks b WHERE (b.user_id=${user.id} AND b.blocked_id=p.user_id) OR (b.blocked_id=${user.id} AND b.user_id=p.user_id)) ORDER BY p.name LIMIT 300`:[];
  const rooms=await sql`SELECT id,name,members,kind,class_id FROM public.campus_rooms WHERE status='approved' AND ${user.id}=ANY(members) ORDER BY created_at DESC LIMIT 100`;
  if(rooms.length){const counts=await sql`SELECT m.room_id,count(*)::integer AS unread,max(m.created_at) AS latest FROM public.campus_messages m LEFT JOIN public.campus_reads r ON r.room_id=m.room_id AND r.user_id=${user.id} WHERE m.room_id=ANY(${rooms.map(r=>r.id)}::uuid[]) AND m.sender_id<>${user.id} AND m.created_at>COALESCE(r.read_at,'epoch'::timestamptz) AND NOT EXISTS(SELECT 1 FROM public.campus_blocks b WHERE (b.user_id=${user.id} AND b.blocked_id=m.sender_id) OR (b.blocked_id=${user.id} AND b.user_id=m.sender_id)) GROUP BY m.room_id`;for(const room of rooms)Object.assign(room,counts.find(c=>c.room_id===room.id)||{unread:0,latest:null});}
  const applications=user.role==='admin'?await sql`SELECT user_id,name,school,subjects FROM public.campus_people WHERE teacher_status='pending' LIMIT 100`:[];
  const reports=user.role==='admin'?await sql`SELECT id,reason,created_at FROM public.campus_reports ORDER BY created_at DESC LIMIT 100`:[];
  const [account]=await sql`SELECT requested_role FROM public.campus_accounts WHERE user_id=${user.id}`;
  return respond(res,200,{...await communityDirectory(sql,user,person,member),role,site,requestedRole:account?.requested_role||'student',person:person||null,member:member||null,notices,people,rooms:await nameRooms(sql,rooms,user.id),applications,reports});
 }
 const body=typeof req.body==='string'?JSON.parse(req.body):req.body;if(!body||JSON.stringify(body).length>40000)err('요청이 너무 큽니다.');const action=str(body.action,40);await limit(sql,user.id,action,['join','join-group'].includes(action)?5:30);
 const handled=await communityActions(sql,user,person,member,role,body);if(handled)return respond(res,200,handled);
 if(action==='profile'){
  const [workspace]=await sql`SELECT data FROM public.radar_workspace WHERE user_id=${user.id}`;const p=workspace?.data?.profile;if(!p?.campusOnboarded)err('먼저 개인 설정을 저장해 주세요.');
  await sql`INSERT INTO public.campus_people(user_id,name,school,grade,class_name,discoverable) VALUES (${user.id},${str(p.name)},${str(p.school)},${str(p.grade)},${str(p.className)},${body.discoverable===true}) ON CONFLICT(user_id) DO UPDATE SET name=EXCLUDED.name,school=EXCLUDED.school,grade=EXCLUDED.grade,class_name=EXCLUDED.class_name,discoverable=EXCLUDED.discoverable,updated_at=now()`;
 }else if(action==='notice'){
  if(!member||!canPublish(role))err('선생님과 임원의 권한입니다',403);if(!site.notices_enabled&&user.role!=='admin')err('관리자가 공지 게시를 잠시 중지했어요.',403);await sql`INSERT INTO public.campus_notices(id,class_id,author_id,title,body) VALUES (${randomUUID()},${member.id},${user.id},${str(body.title,200)},${str(body.text,12000)})`;await notifyPeers(sql,user.id,null,member.id).catch(()=>console.warn('[push]',{status:503}));
 }else if(action==='timetable'){
  if(!member||!['teacher','admin'].includes(role))err('승인된 선생님만 학급 시간표를 편집할 수 있어요.',403);if(!validDate(body.week)||!validTable(body.table)||!validPeriodTimes(body.periodTimes)||(body.daySchedule!==undefined&&!validDaySchedule(body.daySchedule))||(body.examMode!==undefined&&typeof body.examMode!=='boolean'))err('시간표와 교시 시각을 확인해 주세요.');await sql`INSERT INTO public.campus_tables(class_id,week,payload) VALUES (${member.id},${body.week},${JSON.stringify({table:body.table,periodTimes:body.periodTimes,...(body.daySchedule?{daySchedule:body.daySchedule,examMode:!!body.examMode}:{})})}::jsonb) ON CONFLICT(class_id,week) DO UPDATE SET payload=EXCLUDED.payload`;
 }else if(action==='room'){
  if(!person?.discoverable)err('프로필 공개 동의가 필요해요.');if(!Array.isArray(body.members)||body.members.length<1||body.members.length>1||body.members.some(v=>typeof v!=='string'||v===user.id))err('개인 대화는 한 명을 선택하세요. 단체 대화는 그룹 개설을 이용하세요.');const ids=[...new Set(body.members)];
  const peers=await sql`SELECT p.user_id FROM public.campus_people p WHERE p.user_id=ANY(${ids}::text[]) AND p.school=${person.school} AND p.discoverable=true AND NOT EXISTS(SELECT 1 FROM public.campus_accounts a WHERE a.user_id=p.user_id AND a.suspended=true) AND NOT EXISTS(SELECT 1 FROM public.campus_blocks b WHERE (b.user_id=${user.id} AND b.blocked_id=p.user_id) OR (b.user_id=p.user_id AND b.blocked_id=${user.id}))`;if(peers.length!==ids.length)err('동의한 같은 학교 사용자만 초대할 수 있어요.',403);
  if(ids.length===1){const[existing]=await sql`SELECT id FROM public.campus_rooms WHERE kind='direct' AND status='approved' AND cardinality(members)=2 AND members @> ${[user.id,...ids]}::text[] ORDER BY created_at LIMIT 1`;if(existing)return respond(res,200,{id:existing.id});}const [count]=await sql`SELECT count(*)::integer AS n FROM public.campus_rooms WHERE ${user.id}=ANY(members)`;if(count.n>=50)err('대화방은 최대 50개입니다.');const id=randomUUID();await sql`INSERT INTO public.campus_rooms(id,name,members,created_by) VALUES (${id},${str(body.name,100)},${[user.id,...ids]}::text[],${user.id})`;return respond(res,200,{id});
 }else if(action==='message'){
  if(body.clientId!==undefined&&!uuid(body.clientId))err('메시지 식별자를 확인하세요.');if(body.clientId){const [sent]=await sql`SELECT id,room_id FROM public.campus_messages WHERE sender_id=${user.id} AND client_id=${body.clientId}`;if(sent){await roomAccess(sent.room_id);return respond(res,200,{ok:true,id:sent.id,replayed:true});}}
  const targetRoom=await roomAccess(body.roomId);
  if((body.taskId||body.sharedDraft)&&!shareAllowed(targetRoom,role))err('선생님과 임원의 권한입니다',403);
  if((body.taskId||body.sharedDraft)&&!site.sharing_enabled&&user.role!=='admin')err('관리자가 할일 공유를 잠시 중지했어요.',403);
  if(body.taskId||body.sharedDraft){await limit(sql,user.id,'share',5);const date=new Date(Date.now()+9*3600000).toISOString().slice(0,10);const [quota]=await sql`INSERT INTO public.campus_limits(bucket,hits,expires_at) VALUES (${'share-day:'+user.id+':'+date},1,now()+interval '2 days') ON CONFLICT(bucket) DO UPDATE SET hits=campus_limits.hits+1 RETURNING hits`;if(quota.hits>30)err('할일 공유는 하루 30회까지 가능해요.',429);}
  const room=targetRoom,text=typeof body.text==='string'?body.text.trim():'';if(text.length>4000)err('메시지는 4,000자 이내입니다.');const blocked=await sql`SELECT 1 FROM public.campus_blocks WHERE (user_id=${user.id} AND blocked_id=ANY(${room.members}::text[])) OR (blocked_id=${user.id} AND user_id=ANY(${room.members}::text[])) LIMIT 1`;if(room.kind==='direct'&&blocked.length)err('차단 관계가 있는 대화방에는 전송할 수 없어요.',403);
  let shared=null;if(body.sharedDraft){const t=body.sharedDraft;if(typeof t.title!=='string'||!t.title.trim()||t.title.length>200||!validDate(t.due)||!Number.isInteger(t.minutes)||t.minutes<1||t.minutes>10080)err('공유 할일의 제목·마감·소요 시간을 확인하세요.');shared={title:t.title.trim(),fields:{due:t.due,time:null,subject:typeof t.subject==='string'?t.subject.slice(0,100):null},totalMinutes:t.minutes,category:'assignment',taskType:'assignment',priority:2,difficulty:3};}if(body.taskId){const [w]=await sql`SELECT data FROM public.radar_workspace WHERE user_id=${user.id}`;const t=w?.data.tasks.find(t=>t.id===body.taskId);if(!t)err('내 할일을 찾지 못했어요.');shared={title:t.title,fields:{due:t.fields.due,time:t.fields.time,subject:t.fields.subject},totalMinutes:t.totalMinutes??t.minutes,category:t.category,taskType:t.taskType||null,startDate:t.startDate||null,priority:t.priority,difficulty:t.difficulty||3};}if(!text&&!shared)err('메시지 또는 공유할 할일을 선택해 주세요.');const inserted=await sql`INSERT INTO public.campus_messages(id,room_id,sender_id,body,shared,client_id) SELECT ${randomUUID()},r.id,${user.id},${text},${shared?JSON.stringify(shared):null}::jsonb,${body.clientId||null} FROM public.campus_rooms r WHERE r.id=${room.id} AND r.status='approved' AND ${user.id}=ANY(r.members) ON CONFLICT(sender_id,client_id) WHERE client_id IS NOT NULL DO NOTHING RETURNING id`;if(inserted.length)await notifyPeers(sql,user.id,room).catch(()=>console.warn('[push]',{status:503}));
 }else if(action==='read-room'){
  const room=await roomAccess(body.roomId);if(typeof body.through!=='string'||!Number.isFinite(Date.parse(body.through)))err('읽은 시각을 확인하세요.');const through=Date.parse(body.through)>Date.now()?new Date().toISOString():body.through;await sql`INSERT INTO public.campus_reads(user_id,room_id,read_at) VALUES(${user.id},${room.id},${through}) ON CONFLICT(user_id,room_id) DO UPDATE SET read_at=GREATEST(campus_reads.read_at,EXCLUDED.read_at)`;
 }else if(action==='block'){
  if(str(body.userId)===user.id)err('자신은 차단할 수 없어요.');await sql`INSERT INTO public.campus_blocks(user_id,blocked_id) VALUES (${user.id},${body.userId}) ON CONFLICT DO NOTHING`;
 }else if(action==='report'){
  const room=await roomAccess(body.roomId);await sql`INSERT INTO public.campus_reports(id,user_id,room_id,reason) VALUES (${randomUUID()},${user.id},${room.id},${str(body.reason,2000)})`;
 }else err('지원하지 않는 요청입니다.');
 return respond(res,200,{ok:true});
}catch(error){console.warn('[campus]',{method:req.method,status:error.status||503,code:error.code||null});fail(res,error);}}
